using System.Collections.Generic;
using Windows.System.UserProfile;

namespace Tick.Services;

/// <summary>
/// 语言本地化：简体中文 / 繁體中文 / 日本語 / 한국어 / English / Français / Deutsch / Español 八套文本表。
/// 支持「跟随系统」（<see cref="GlobalizationPreferences"/> 解析出上述之一）。
/// 静态文本（XAML）经 <see cref="L"/> 标记扩展读取；代码动态字符串用 <see cref="Tr"/>。
/// 切换语言后由 MainWindow 重新导航当前页触发 XAML 重建，从而即时生效。
/// </summary>
public static class Localization
{
    private static string _lang = "zh";

    /// <summary>当前语言码（"system" 已被解析为具体 8 语言码之一）</summary>
    public static string Language => _lang;

    /// <summary>兼容旧调用：是否 English</summary>
    public static bool IsEnglish => _lang == "en";

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["app.title"] = "Tick 待办",
        ["nav.goals"] = "目标",
        ["nav.ai"] = "AI 助手",
        ["nav.settings"] = "设置",

        ["goals.add"] = "新建目标",
        ["goals.edit"] = "编辑目标",
        ["goals.delete"] = "删除目标",
        ["goals.deleteConfirm"] = "确定删除目标“{0}”吗？其下全部任务将一并删除。",
        ["goals.empty"] = "还没有目标，点击下方「新建目标」创建",

        ["tasks.title"] = "任务",
        ["tasks.progress"] = "总进度",
        ["tasks.completed"] = "已完成 {0}/{1}",
        ["tasks.countdown"] = "倒计时",
        ["tasks.add"] = "添加任务",
        ["tasks.addSubtask"] = "添加子任务",
        ["tasks.edit"] = "编辑任务",
        ["tasks.delete"] = "删除任务",
        ["tasks.deleteConfirm"] = "确定删除任务“{0}”吗？其下全部子任务将一并删除。",
        ["tasks.noEndDate"] = "未设置截止日期",

        ["task.name"] = "名称",
        ["task.type"] = "类型",
        ["task.single"] = "单项",
        ["task.progress"] = "进度",
        ["task.status"] = "状态",
        ["task.notDone"] = "未完成",
        ["task.halfDone"] = "半完成",
        ["task.done"] = "完成",
        ["task.deleted"] = "删除",
        ["task.total"] = "总量",
        ["task.current"] = "当前",
        ["task.color"] = "颜色",
        ["task.color.auto"] = "自动",
        ["task.startDate"] = "开始日期",
        ["task.endDate"] = "截止日期",
        ["task.preciseToHour"] = "精确到小时",
        ["task.reminder"] = "提醒",
        ["task.inherited"] = "（继承父级）",
        ["task.takenOver"] = "（由子任务接管）",

        ["repeat.never"] = "不重复",
        ["repeat.daily"] = "每天",
        ["repeat.weekly"] = "每周",
        ["repeat.monthly"] = "每月",
        ["repeat.custom"] = "自定义",
        ["weekday.1"] = "周日",
        ["weekday.2"] = "周一",
        ["weekday.3"] = "周二",
        ["weekday.4"] = "周三",
        ["weekday.5"] = "周四",
        ["weekday.6"] = "周五",
        ["weekday.7"] = "周六",

        ["common.cancel"] = "取消",
        ["common.ok"] = "确定",
        ["common.save"] = "保存",
        ["common.name"] = "名称",
        ["common.error"] = "错误",
        ["common.notice"] = "提示",
        ["common.warning"] = "警告",

        ["settings.title"] = "设置",
        ["settings.theme"] = "配色方案",
        ["theme.system"] = "跟随系统",
        ["theme.light"] = "亮色",
        ["theme.dark"] = "暗色",
        ["settings.language"] = "语言",
        ["lang.system"] = "跟随系统",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "AI 配置",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows 无公开的第三方本地大模型 API，因此不内嵌 AI。可在下方配置任一 OpenAI 兼容模型的 API Key，聊天 / 生成任务会走该接口。",
        ["settings.copilotOpen"] = "打开 Copilot",
        ["settings.model"] = "模型",
        ["settings.apiKey"] = "API Key（DPAPI 加密存储）",
        ["settings.baseUrl"] = "Base URL",
        ["settings.modelId"] = "模型名称",
        ["settings.backup"] = "备份 / 恢复",
        ["settings.export"] = "导出为 JSON 文件",
        ["settings.import"] = "从 JSON 文件导入",
        ["settings.importConfirm"] = "导入将合并当前数据库（已有目标按 Id 覆盖）。是否继续？",
        ["settings.documents"] = "附件解析",
        ["settings.documentsHint"] = "支持 .txt / .md / Markdown / .docx；.pdf 需第三方库，本版本未内置。",

        ["ai.title"] = "AI 助手",
        ["ai.hint"] = "描述你想规划的事项，或上传附件让 AI 提炼任务。AI 会输出 JSON：generate=true 时任务树直接写入当前目标。",
        ["ai.input"] = "输入消息…",
        ["ai.send"] = "发送",
        ["ai.attach"] = "附件",
        ["ai.clear"] = "清空对话",
        ["ai.noAttachText"] = "该附件暂无法解析（仅支持 .txt/.md/.docx）",
        ["ai.notConfigured"] = "尚未配置 API Key，请在 设置 → AI 模型 中填写。",
        ["ai.sending"] = "正在思考…",
        ["ai.generated"] = "已将生成的任务写入当前目标。",
        ["ai.history"] = "历史会话",
        ["ai.noHistory"] = "暂无历史会话",

        ["tasks.remaining"] = "剩余时间",
        ["tasks.aiImport"] = "AI 导入",
        ["tasks.deleteNoSub"] = "确定删除任务“{0}”吗？",
        ["task.repeat"] = "重复",
        ["task.invalidNumber"] = "请输入有效的数字",
        ["task.reminderDate"] = "提醒日期",
        ["task.reminderTime"] = "提醒时间",
        ["ai.newChat"] = "新建聊天",
        ["ai.welcome"] = "你好！我是你的任务规划助手。描述你想规划的事项，或附加文档让我提炼任务清单。",
        ["ai.deleteSession"] = "确定删除该历史会话吗？",
        ["settings.saved"] = "设置已保存",
        ["settings.exportOk"] = "已导出备份文件",
        ["settings.importOk"] = "导入完成，共恢复 {0} 个目标",

        // ---- 扩展：统计模式 / 色板 / 模型名 / 校验 / 通知 / 文档 / AI 错误 / 倒计时 ----
        ["task.counting.header"] = "统计模式",
        ["task.counting.all"] = "全部任务",
        ["task.counting.leaf"] = "仅叶子任务",

        ["color.black"] = "黑色",
        ["color.red"] = "红色",
        ["color.orange"] = "橙色",
        ["color.yellow"] = "黄色",
        ["color.green"] = "绿色",
        ["color.mint"] = "薄荷绿",
        ["color.teal"] = "青色",
        ["color.blue"] = "蓝色",
        ["color.indigo"] = "靛蓝",
        ["color.purple"] = "紫色",
        ["color.pink"] = "粉色",
        ["color.brown"] = "棕色",

        ["ai.model.qwen"] = "千问",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "元宝",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "文心",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "阶跃星辰",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "自定义",

        ["validation.goal.nameEmpty"] = "目标名称不能为空",
        ["validation.task.nameEmpty"] = "任务名称不能为空",

        ["toast.goalPrefix"] = "目标：{0}",
        ["backup.invalid"] = "备份文件格式无效",

        ["doc.unsupportedDoc"] = "旧版 .doc 暂不支持，请另存为 .docx 后重试",
        ["doc.pdfDisabled"] = "PDF 附件暂未启用（需文本抽取库）",
        ["doc.unsupportedType"] = "暂不支持该文件类型，请使用文本或 Markdown 文档",
        ["doc.noText"] = "未能从文档中读取到文字内容",
        ["doc.invalidWord"] = "无法解析该 Word 文档",

        ["ai.error.noApiKey"] = "请先在 设置 → AI 模型 中填写该模型的 API Key",
        ["ai.error.customBaseUrl"] = "自定义模型需要在设置中填写 Base URL",
        ["ai.error.emptyInput"] = "请先输入内容",
        ["ai.error.invalidUrl"] = "模型服务地址无效",
        ["ai.error.httpError"] = "模型服务返回异常：HTTP {0}",
        ["ai.error.badResponse"] = "模型服务返回了异常响应",
        ["ai.generatedCount"] = "已为你生成 {0} 个任务。",
        ["tasks.aiImportPrompt"] = "请根据附件内容生成任务清单",

        ["countdown.yearMonth"] = "{0}年{1}月",
        ["countdown.year"] = "{0}年",
        ["countdown.monthDay"] = "{0}月{1}日",
        ["countdown.month"] = "{0}月",
        ["countdown.dayHour"] = "{0}日{1}时",
        ["countdown.day"] = "{0}日",
        ["countdown.hour"] = "{0}时",
    };

    private static readonly Dictionary<string, string> ZhHant = new()
    {
        ["app.title"] = "Tick 待辦",
        ["nav.goals"] = "目標",
        ["nav.ai"] = "AI 助手",
        ["nav.settings"] = "設定",

        ["goals.add"] = "新建目標",
        ["goals.edit"] = "編輯目標",
        ["goals.delete"] = "刪除目標",
        ["goals.deleteConfirm"] = "確定刪除目標「{0}」嗎？其下全部任務將一併刪除。",
        ["goals.empty"] = "還沒有目標，點擊下方「新建目標」建立",

        ["tasks.title"] = "任務",
        ["tasks.progress"] = "總進度",
        ["tasks.completed"] = "已完成 {0}/{1}",
        ["tasks.countdown"] = "倒數計時",
        ["tasks.add"] = "新增任務",
        ["tasks.addSubtask"] = "新增子任務",
        ["tasks.edit"] = "編輯任務",
        ["tasks.delete"] = "刪除任務",
        ["tasks.deleteConfirm"] = "確定刪除任務「{0}」嗎？其下全部子任務將一併刪除。",
        ["tasks.noEndDate"] = "未設定截止日期",

        ["task.name"] = "名稱",
        ["task.type"] = "類型",
        ["task.single"] = "單項",
        ["task.progress"] = "進度",
        ["task.status"] = "狀態",
        ["task.notDone"] = "未完成",
        ["task.halfDone"] = "半完成",
        ["task.done"] = "完成",
        ["task.deleted"] = "刪除",
        ["task.total"] = "總量",
        ["task.current"] = "目前",
        ["task.color"] = "顏色",
        ["task.color.auto"] = "自動",
        ["task.startDate"] = "開始日期",
        ["task.endDate"] = "截止日期",
        ["task.preciseToHour"] = "精確到小時",
        ["task.reminder"] = "提醒",
        ["task.inherited"] = "（繼承父級）",
        ["task.takenOver"] = "（由子任務接管）",

        ["repeat.never"] = "不重複",
        ["repeat.daily"] = "每天",
        ["repeat.weekly"] = "每週",
        ["repeat.monthly"] = "每月",
        ["repeat.custom"] = "自訂",
        ["weekday.1"] = "週日",
        ["weekday.2"] = "週一",
        ["weekday.3"] = "週二",
        ["weekday.4"] = "週三",
        ["weekday.5"] = "週四",
        ["weekday.6"] = "週五",
        ["weekday.7"] = "週六",

        ["common.cancel"] = "取消",
        ["common.ok"] = "確定",
        ["common.save"] = "儲存",
        ["common.name"] = "名稱",
        ["common.error"] = "錯誤",
        ["common.notice"] = "提示",
        ["common.warning"] = "警告",

        ["settings.title"] = "設定",
        ["settings.theme"] = "配色方案",
        ["theme.system"] = "跟隨系統",
        ["theme.light"] = "亮色",
        ["theme.dark"] = "暗色",
        ["settings.language"] = "語言",
        ["lang.system"] = "跟隨系統",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "AI 配置",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows 沒有公開的第三方本地大模型 API，因此不內嵌 AI。可在下方配置任一 OpenAI 相容模型的 API Key，聊天／生成任務會走該介面。",
        ["settings.copilotOpen"] = "開啟 Copilot",
        ["settings.model"] = "模型",
        ["settings.apiKey"] = "API Key（DPAPI 加密儲存）",
        ["settings.baseUrl"] = "Base URL",
        ["settings.modelId"] = "模型名稱",
        ["settings.backup"] = "備份／還原",
        ["settings.export"] = "匯出為 JSON 檔案",
        ["settings.import"] = "從 JSON 檔案匯入",
        ["settings.importConfirm"] = "匯入將合併目前資料庫（已有目標依 Id 覆寫）。是否繼續？",
        ["settings.documents"] = "附件解析",
        ["settings.documentsHint"] = "支援 .txt / .md / Markdown / .docx；.pdf 需要第三方程式庫，本版本未內建。",

        ["ai.title"] = "AI 助手",
        ["ai.hint"] = "描述你想規劃的事項，或上傳附件讓 AI 提煉任務。AI 會輸出 JSON：generate=true 時任務樹會直接寫入目前目標。",
        ["ai.input"] = "輸入訊息…",
        ["ai.send"] = "傳送",
        ["ai.attach"] = "附件",
        ["ai.clear"] = "清空對話",
        ["ai.noAttachText"] = "該附件暫時無法解析（僅支援 .txt/.md/.docx）",
        ["ai.notConfigured"] = "尚未配置 API Key，請在 設定 → AI 模型 中填寫。",
        ["ai.sending"] = "正在思考…",
        ["ai.generated"] = "已將產生的任務寫入目前目標。",
        ["ai.history"] = "歷史對話",
        ["ai.noHistory"] = "暫無歷史對話",

        ["tasks.remaining"] = "剩餘時間",
        ["tasks.aiImport"] = "AI 匯入",
        ["tasks.deleteNoSub"] = "確定刪除任務「{0}」嗎？",
        ["task.repeat"] = "重複",
        ["task.invalidNumber"] = "請輸入有效的數字",
        ["task.reminderDate"] = "提醒日期",
        ["task.reminderTime"] = "提醒時間",
        ["ai.newChat"] = "新增對話",
        ["ai.welcome"] = "你好！我是你的任務規劃助手。描述你想規劃的事項，或附加文件讓我提煉任務清單。",
        ["ai.deleteSession"] = "確定刪除該歷史對話嗎？",
        ["settings.saved"] = "設定已儲存",
        ["settings.exportOk"] = "已匯出備份檔案",
        ["settings.importOk"] = "匯入完成，共還原 {0} 個目標",

        // ---- 擴充：統計模式 / 色板 / 模型名 / 驗證 / 通知 / 文件 / AI 錯誤 / 倒數 ----
        ["task.counting.header"] = "統計模式",
        ["task.counting.all"] = "全部任務",
        ["task.counting.leaf"] = "僅葉子任務",

        ["color.black"] = "黑色",
        ["color.red"] = "紅色",
        ["color.orange"] = "橙色",
        ["color.yellow"] = "黃色",
        ["color.green"] = "綠色",
        ["color.mint"] = "薄荷綠",
        ["color.teal"] = "青色",
        ["color.blue"] = "藍色",
        ["color.indigo"] = "靛藍",
        ["color.purple"] = "紫色",
        ["color.pink"] = "粉色",
        ["color.brown"] = "棕色",

        ["ai.model.qwen"] = "千問",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "元寶",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "文心",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "階躍星辰",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "自訂",

        ["validation.goal.nameEmpty"] = "目標名稱不能為空",
        ["validation.task.nameEmpty"] = "任務名稱不能為空",

        ["toast.goalPrefix"] = "目標：{0}",
        ["backup.invalid"] = "備份檔案格式無效",

        ["doc.unsupportedDoc"] = "舊版 .doc 暫不支援，請另存為 .docx 後重試",
        ["doc.pdfDisabled"] = "PDF 附件暫未啟用（需文字擷取程式庫）",
        ["doc.unsupportedType"] = "暫不支援該檔案類型，請使用文字或 Markdown 文件",
        ["doc.noText"] = "未能從文件中讀取到文字內容",
        ["doc.invalidWord"] = "無法解析該 Word 文件",

        ["ai.error.noApiKey"] = "請先在 設定 → AI 模型中填寫該模型的 API Key",
        ["ai.error.customBaseUrl"] = "自訂模型需要在設定中填寫 Base URL",
        ["ai.error.emptyInput"] = "請先輸入內容",
        ["ai.error.invalidUrl"] = "模型服務位址無效",
        ["ai.error.httpError"] = "模型服務傳回異常：HTTP {0}",
        ["ai.error.badResponse"] = "模型服務傳回了異常回應",
        ["ai.generatedCount"] = "已為你產生 {0} 個任務。",
        ["tasks.aiImportPrompt"] = "請根據附件內容產生任務清單",

        ["countdown.yearMonth"] = "{0}年{1}月",
        ["countdown.year"] = "{0}年",
        ["countdown.monthDay"] = "{0}月{1}日",
        ["countdown.month"] = "{0}月",
        ["countdown.dayHour"] = "{0}日{1}時",
        ["countdown.day"] = "{0}日",
        ["countdown.hour"] = "{0}時",
    };

    private static readonly Dictionary<string, string> Ja = new()
    {
        ["app.title"] = "Tick Todo",
        ["nav.goals"] = "目標",
        ["nav.ai"] = "AI アシスタント",
        ["nav.settings"] = "設定",

        ["goals.add"] = "新規目標",
        ["goals.edit"] = "目標を編集",
        ["goals.delete"] = "目標を削除",
        ["goals.deleteConfirm"] = "目標「{0}」を削除しますか？配下のすべてのタスクも削除されます。",
        ["goals.empty"] = "目標はまだありません。下の「新規目標」をタップして作成してください",

        ["tasks.title"] = "タスク",
        ["tasks.progress"] = "全体の進捗",
        ["tasks.completed"] = "完了 {0}/{1}",
        ["tasks.countdown"] = "カウントダウン",
        ["tasks.add"] = "タスクを追加",
        ["tasks.addSubtask"] = "サブタスクを追加",
        ["tasks.edit"] = "タスクを編集",
        ["tasks.delete"] = "タスクを削除",
        ["tasks.deleteConfirm"] = "タスク「{0}」を削除しますか？配下のすべてのサブタスクも削除されます。",
        ["tasks.noEndDate"] = "期限日なし",

        ["task.name"] = "名前",
        ["task.type"] = "種類",
        ["task.single"] = "単項目",
        ["task.progress"] = "進捗",
        ["task.status"] = "ステータス",
        ["task.notDone"] = "未完了",
        ["task.halfDone"] = "半完了",
        ["task.done"] = "完了",
        ["task.deleted"] = "削除",
        ["task.total"] = "合計量",
        ["task.current"] = "現在",
        ["task.color"] = "カラー",
        ["task.color.auto"] = "自動",
        ["task.startDate"] = "開始日",
        ["task.endDate"] = "期限日",
        ["task.preciseToHour"] = "時間単位まで指定",
        ["task.reminder"] = "リマインダー",
        ["task.inherited"] = "（親から継承）",
        ["task.takenOver"] = "（サブタスクが引き継いだ）",

        ["repeat.never"] = "繰り返しなし",
        ["repeat.daily"] = "毎日",
        ["repeat.weekly"] = "毎週",
        ["repeat.monthly"] = "毎月",
        ["repeat.custom"] = "カスタム",
        ["weekday.1"] = "日曜日",
        ["weekday.2"] = "月曜日",
        ["weekday.3"] = "火曜日",
        ["weekday.4"] = "水曜日",
        ["weekday.5"] = "木曜日",
        ["weekday.6"] = "金曜日",
        ["weekday.7"] = "土曜日",

        ["common.cancel"] = "キャンセル",
        ["common.ok"] = "OK",
        ["common.save"] = "保存",
        ["common.name"] = "名前",
        ["common.error"] = "エラー",
        ["common.notice"] = "通知",
        ["common.warning"] = "警告",

        ["settings.title"] = "設定",
        ["settings.theme"] = "カラーテーマ",
        ["theme.system"] = "システムに従う",
        ["theme.light"] = "ライト",
        ["theme.dark"] = "ダーク",
        ["settings.language"] = "言語",
        ["lang.system"] = "システムに従う",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "AI 設定",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows には公開されたサードパーティ製ローカル LLM API がないため、AI は内蔵されていません。下記で OpenAI 互換モデルの API Key を設定すると、チャット／タスク生成はその API を使用します。",
        ["settings.copilotOpen"] = "Copilot を開く",
        ["settings.model"] = "モデル",
        ["settings.apiKey"] = "API Key（DPAPI で暗号化して保存）",
        ["settings.baseUrl"] = "Base URL",
        ["settings.modelId"] = "モデル名",
        ["settings.backup"] = "バックアップ／復元",
        ["settings.export"] = "JSON ファイルに書き出す",
        ["settings.import"] = "JSON ファイルから読み込む",
        ["settings.importConfirm"] = "インポートすると現在のデータベースにマージされます（既存の目標は Id で上書き）。続行しますか？",
        ["settings.documents"] = "添付ファイル解析",
        ["settings.documentsHint"] = ".txt / .md / Markdown / .docx に対応。.pdf はサードパーティ製ライブラリが必要で、本バージョンには未搭載です。",

        ["ai.title"] = "AI アシスタント",
        ["ai.hint"] = "計画したいことを説明するか、添付ファイルをアップロードして AI にタスクを抽出させてください。AI は JSON を出力します：generate=true の場合、タスクツリーを現在の目標に直接書き込みます。",
        ["ai.input"] = "メッセージを入力…",
        ["ai.send"] = "送信",
        ["ai.attach"] = "添付",
        ["ai.clear"] = "チャットをクリア",
        ["ai.noAttachText"] = "この添付ファイルは解析できません（.txt/.md/.docx のみ対応）",
        ["ai.notConfigured"] = "API Key が設定されていません。設定 → AI モデルで入力してください。",
        ["ai.sending"] = "考え中…",
        ["ai.generated"] = "生成されたタスクを現在の目標に書き込みました。",
        ["ai.history"] = "履歴",
        ["ai.noHistory"] = "履歴はありません",

        ["tasks.remaining"] = "残り時間",
        ["tasks.aiImport"] = "AI インポート",
        ["tasks.deleteNoSub"] = "タスク「{0}」を削除しますか？",
        ["task.repeat"] = "繰り返し",
        ["task.invalidNumber"] = "有効な数値を入力してください",
        ["task.reminderDate"] = "リマインダー日",
        ["task.reminderTime"] = "リマインダー時刻",
        ["ai.newChat"] = "新しいチャット",
        ["ai.welcome"] = "こんにちは！私はあなたのタスク計画アシスタントです。計画したいことを説明するか、文書を添付してタスクリストに変換できます。",
        ["ai.deleteSession"] = "この履歴セッションを削除しますか？",
        ["settings.saved"] = "設定を保存しました",
        ["settings.exportOk"] = "バックアップファイルを書き出しました",
        ["settings.importOk"] = "インポート完了：{0} 個の目標を復元しました",

        // ---- 追加：集計モード / カラー / モデル名 / 検証 / 通知 / 文書 / AI エラー / カウントダウン ----
        ["task.counting.header"] = "集計モード",
        ["task.counting.all"] = "すべてのタスク",
        ["task.counting.leaf"] = "葉タスクのみ",

        ["color.black"] = "黒",
        ["color.red"] = "赤",
        ["color.orange"] = "オレンジ",
        ["color.yellow"] = "黄",
        ["color.green"] = "緑",
        ["color.mint"] = "ミントグリーン",
        ["color.teal"] = "シアン",
        ["color.blue"] = "青",
        ["color.indigo"] = "インディゴ",
        ["color.purple"] = "紫",
        ["color.pink"] = "ピンク",
        ["color.brown"] = "ブラウン",

        ["ai.model.qwen"] = "Qwen",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "Yuanbao",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "ERNIE",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "StepFun",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "カスタム",

        ["validation.goal.nameEmpty"] = "目標名を入力してください",
        ["validation.task.nameEmpty"] = "タスク名を入力してください",

        ["toast.goalPrefix"] = "目標：{0}",
        ["backup.invalid"] = "バックアップファイルの形式が無効です",

        ["doc.unsupportedDoc"] = "旧形式の .doc は未対応です。.docx として保存してから再試行してください",
        ["doc.pdfDisabled"] = "PDF 添付はまだ有効になっていません（テキスト抽出ライブラリが必要）",
        ["doc.unsupportedType"] = "このファイル形式は未対応です。テキストまたは Markdown 文書を使用してください",
        ["doc.noText"] = "文書からテキストを読み取れませんでした",
        ["doc.invalidWord"] = "この Word 文書を解析できません",

        ["ai.error.noApiKey"] = "まず「設定 → AI モデル」でこのモデルの API Key を入力してください",
        ["ai.error.customBaseUrl"] = "カスタムモデルは設定で Base URL を入力する必要があります",
        ["ai.error.emptyInput"] = "先に内容を入力してください",
        ["ai.error.invalidUrl"] = "モデルサービスのアドレスが無効です",
        ["ai.error.httpError"] = "モデルサービスが異常を返しました：HTTP {0}",
        ["ai.error.badResponse"] = "モデルサービスが異常な応答を返しました",
        ["ai.generatedCount"] = "{0} 件のタスクを生成しました。",
        ["tasks.aiImportPrompt"] = "添付ファイルの内容に基づいてタスクリストを生成してください",

        ["countdown.yearMonth"] = "{0}年{1}か月",
        ["countdown.year"] = "{0}年",
        ["countdown.monthDay"] = "{0}か月{1}日",
        ["countdown.month"] = "{0}か月",
        ["countdown.dayHour"] = "{0}日{1}時間",
        ["countdown.day"] = "{0}日",
        ["countdown.hour"] = "{0}時間",
    };

    private static readonly Dictionary<string, string> Ko = new()
    {
        ["app.title"] = "Tick 할 일",
        ["nav.goals"] = "목표",
        ["nav.ai"] = "AI 어시스턴트",
        ["nav.settings"] = "설정",

        ["goals.add"] = "새 목표",
        ["goals.edit"] = "목표 편집",
        ["goals.delete"] = "목표 삭제",
        ["goals.deleteConfirm"] = "목표 \"{0}\"을(를) 삭제할까요? 아래의 모든 작업도 함께 삭제됩니다.",
        ["goals.empty"] = "아직 목표가 없습니다. 아래의 「새 목표」를 눌러 만드세요",

        ["tasks.title"] = "작업",
        ["tasks.progress"] = "전체 진행률",
        ["tasks.completed"] = "완료 {0}/{1}",
        ["tasks.countdown"] = "카운트다운",
        ["tasks.add"] = "작업 추가",
        ["tasks.addSubtask"] = "하위 작업 추가",
        ["tasks.edit"] = "작업 편집",
        ["tasks.delete"] = "작업 삭제",
        ["tasks.deleteConfirm"] = "작업 \"{0}\"을(를) 삭제할까요? 아래의 모든 하위 작업도 함께 삭제됩니다.",
        ["tasks.noEndDate"] = "마감일 없음",

        ["task.name"] = "이름",
        ["task.type"] = "유형",
        ["task.single"] = "단일 항목",
        ["task.progress"] = "진행률",
        ["task.status"] = "상태",
        ["task.notDone"] = "미완료",
        ["task.halfDone"] = "반 완료",
        ["task.done"] = "완료",
        ["task.deleted"] = "삭제",
        ["task.total"] = "총량",
        ["task.current"] = "현재",
        ["task.color"] = "색상",
        ["task.color.auto"] = "자동",
        ["task.startDate"] = "시작일",
        ["task.endDate"] = "마감일",
        ["task.preciseToHour"] = "시간 단위 지정",
        ["task.reminder"] = "알림",
        ["task.inherited"] = "（상위에서 상속）",
        ["task.takenOver"] = "（하위 작업이 인계했음）",

        ["repeat.never"] = "반복 없음",
        ["repeat.daily"] = "매일",
        ["repeat.weekly"] = "매주",
        ["repeat.monthly"] = "매월",
        ["repeat.custom"] = "사용자 지정",
        ["weekday.1"] = "일요일",
        ["weekday.2"] = "월요일",
        ["weekday.3"] = "화요일",
        ["weekday.4"] = "수요일",
        ["weekday.5"] = "목요일",
        ["weekday.6"] = "금요일",
        ["weekday.7"] = "토요일",

        ["common.cancel"] = "취소",
        ["common.ok"] = "확인",
        ["common.save"] = "저장",
        ["common.name"] = "이름",
        ["common.error"] = "오류",
        ["common.notice"] = "알림",
        ["common.warning"] = "경고",

        ["settings.title"] = "설정",
        ["settings.theme"] = "색상 테마",
        ["theme.system"] = "시스템 따르기",
        ["theme.light"] = "라이트",
        ["theme.dark"] = "다크",
        ["settings.language"] = "언어",
        ["lang.system"] = "시스템 따르기",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "AI 설정",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows에는 공개된 타사 로컬 대형 모델 API가 없으므로 AI가 내장되어 있지 않습니다. 아래에서 OpenAI 호환 모델의 API Key를 구성하면 채팅/작업 생성이 해당 인터페이스를 사용합니다.",
        ["settings.copilotOpen"] = "Copilot 열기",
        ["settings.model"] = "모델",
        ["settings.apiKey"] = "API Key（DPAPI로 암호화 저장）",
        ["settings.baseUrl"] = "Base URL",
        ["settings.modelId"] = "모델 이름",
        ["settings.backup"] = "백업/복원",
        ["settings.export"] = "JSON 파일로 내보내기",
        ["settings.import"] = "JSON 파일에서 가져오기",
        ["settings.importConfirm"] = "가져오면 현재 데이터베이스에 병합됩니다(기존 목표는 Id 기준으로 덮어씀). 계속할까요?",
        ["settings.documents"] = "첨부 파일 분석",
        ["settings.documentsHint"] = ".txt / .md / Markdown / .docx 지원. .pdf는 타사 라이브러리가 필요하며 이 버전에는 포함되어 있지 않습니다.",

        ["ai.title"] = "AI 어시스턴트",
        ["ai.hint"] = "계획할 내용을 설명하거나 첨부 파일을 올려 AI가 작업을 추출하도록 하세요. AI는 JSON을 출력합니다: generate=true면 작업 트리가 현재 목표에 직접 기록됩니다.",
        ["ai.input"] = "메시지 입력…",
        ["ai.send"] = "보내기",
        ["ai.attach"] = "첨부",
        ["ai.clear"] = "대화 지우기",
        ["ai.noAttachText"] = "이 첨부 파일은 분석할 수 없습니다(.txt/.md/.docx만 지원)",
        ["ai.notConfigured"] = "API Key가 구성되어 있지 않습니다. 설정 → AI 모델에서 입력하세요.",
        ["ai.sending"] = "생각하는 중…",
        ["ai.generated"] = "생성된 작업을 현재 목표에 기록했습니다.",
        ["ai.history"] = "기록",
        ["ai.noHistory"] = "기록이 없습니다",

        ["tasks.remaining"] = "남은 시간",
        ["tasks.aiImport"] = "AI 가져오기",
        ["tasks.deleteNoSub"] = "작업 \"{0}\"을(를) 삭제할까요?",
        ["task.repeat"] = "반복",
        ["task.invalidNumber"] = "유효한 숫자를 입력하세요",
        ["task.reminderDate"] = "알림 날짜",
        ["task.reminderTime"] = "알림 시간",
        ["ai.newChat"] = "새 채팅",
        ["ai.welcome"] = "안녕하세요! 저는 여러분의 작업 계획 도우미입니다. 계획할 내용을 설명하거나 문서를 첨부하면 작업 목록으로 변환해 드립니다.",
        ["ai.deleteSession"] = "이 기록 세션을 삭제할까요?",
        ["settings.saved"] = "설정 저장됨",
        ["settings.exportOk"] = "백업 파일 내보냄",
        ["settings.importOk"] = "가져오기 완료: 목표 {0}개 복원",

        // ---- 확장: 집계 모드 / 색상 / 모델 이름 / 유효성 검사 / 알림 / 문서 / AI 오류 / 카운트다운 ----
        ["task.counting.header"] = "집계 모드",
        ["task.counting.all"] = "모든 작업",
        ["task.counting.leaf"] = "리프 작업만",

        ["color.black"] = "검정",
        ["color.red"] = "빨강",
        ["color.orange"] = "주황",
        ["color.yellow"] = "노랑",
        ["color.green"] = "초록",
        ["color.mint"] = "민트 그린",
        ["color.teal"] = "청록",
        ["color.blue"] = "파랑",
        ["color.indigo"] = "남색",
        ["color.purple"] = "보라",
        ["color.pink"] = "분홍",
        ["color.brown"] = "갈색",

        ["ai.model.qwen"] = "Qwen",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "Yuanbao",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "ERNIE",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "StepFun",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "사용자 지정",

        ["validation.goal.nameEmpty"] = "목표 이름을 입력하세요",
        ["validation.task.nameEmpty"] = "작업 이름을 입력하세요",

        ["toast.goalPrefix"] = "목표: {0}",
        ["backup.invalid"] = "백업 파일 형식이 올바르지 않습니다",

        ["doc.unsupportedDoc"] = "이전 버전 .doc은 지원하지 않습니다. .docx로 저장한 후 다시 시도하세요",
        ["doc.pdfDisabled"] = "PDF 첨부는 아직 지원되지 않습니다(텍스트 추출 라이브러리 필요)",
        ["doc.unsupportedType"] = "지원하지 않는 파일 형식입니다. 텍스트 또는 Markdown 문서를 사용하세요",
        ["doc.noText"] = "문서에서 텍스트를 읽을 수 없습니다",
        ["doc.invalidWord"] = "이 Word 문서를 분석할 수 없습니다",

        ["ai.error.noApiKey"] = "먼저 설정 → AI 모델에서 이 모델의 API Key를 입력하세요",
        ["ai.error.customBaseUrl"] = "사용자 지정 모델은 설정에서 Base URL을 입력해야 합니다",
        ["ai.error.emptyInput"] = "먼저 내용을 입력하세요",
        ["ai.error.invalidUrl"] = "모델 서비스 주소가 올바르지 않습니다",
        ["ai.error.httpError"] = "모델 서비스가 오류를 반환했습니다: HTTP {0}",
        ["ai.error.badResponse"] = "모델 서비스가 비정상 응답을 반환했습니다",
        ["ai.generatedCount"] = "작업 {0}개를 생성했습니다.",
        ["tasks.aiImportPrompt"] = "첨부 파일 내용에 따라 작업 목록을 생성하세요",

        ["countdown.yearMonth"] = "{0}년 {1}개월",
        ["countdown.year"] = "{0}년",
        ["countdown.monthDay"] = "{0}개월 {1}일",
        ["countdown.month"] = "{0}개월",
        ["countdown.dayHour"] = "{0}일 {1}시간",
        ["countdown.day"] = "{0}일",
        ["countdown.hour"] = "{0}시간",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "Tick Todo",
        ["nav.goals"] = "Goals",
        ["nav.ai"] = "AI Assistant",
        ["nav.settings"] = "Settings",

        ["goals.add"] = "New Goal",
        ["goals.edit"] = "Edit Goal",
        ["goals.delete"] = "Delete Goal",
        ["goals.deleteConfirm"] = "Delete goal \"{0}\"? All its tasks will be removed.",
        ["goals.empty"] = "No goals yet. Tap \"New Goal\" below to create one.",

        ["tasks.title"] = "Tasks",
        ["tasks.progress"] = "Progress",
        ["tasks.completed"] = "Done {0}/{1}",
        ["tasks.countdown"] = "Countdown",
        ["tasks.add"] = "Add Task",
        ["tasks.addSubtask"] = "Add Subtask",
        ["tasks.edit"] = "Edit Task",
        ["tasks.delete"] = "Delete Task",
        ["tasks.deleteConfirm"] = "Delete task \"{0}\"? All its subtasks will be removed.",
        ["tasks.noEndDate"] = "No due date",

        ["task.name"] = "Name",
        ["task.type"] = "Type",
        ["task.single"] = "Single",
        ["task.progress"] = "Progress",
        ["task.status"] = "Status",
        ["task.notDone"] = "Not done",
        ["task.halfDone"] = "Half done",
        ["task.done"] = "Done",
        ["task.deleted"] = "Deleted",
        ["task.total"] = "Total",
        ["task.current"] = "Current",
        ["task.color"] = "Color",
        ["task.color.auto"] = "Auto",
        ["task.startDate"] = "Start date",
        ["task.endDate"] = "Due date",
        ["task.preciseToHour"] = "Precise to hour",
        ["task.reminder"] = "Reminder",
        ["task.inherited"] = "(inherit)",
        ["task.takenOver"] = "(taken over by subtasks)",

        ["repeat.never"] = "Never",
        ["repeat.daily"] = "Daily",
        ["repeat.weekly"] = "Weekly",
        ["repeat.monthly"] = "Monthly",
        ["repeat.custom"] = "Custom",
        ["weekday.1"] = "Sun",
        ["weekday.2"] = "Mon",
        ["weekday.3"] = "Tue",
        ["weekday.4"] = "Wed",
        ["weekday.5"] = "Thu",
        ["weekday.6"] = "Fri",
        ["weekday.7"] = "Sat",

        ["common.cancel"] = "Cancel",
        ["common.ok"] = "OK",
        ["common.save"] = "Save",
        ["common.name"] = "Name",
        ["common.error"] = "Error",
        ["common.notice"] = "Notice",
        ["common.warning"] = "Warning",

        ["settings.title"] = "Settings",
        ["settings.theme"] = "Color scheme",
        ["theme.system"] = "Follow system",
        ["theme.light"] = "Light",
        ["theme.dark"] = "Dark",
        ["settings.language"] = "Language",
        ["lang.system"] = "Follow system",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "AI Configuration",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows has no public third-party on-device LLM API, so no AI is embedded here. Configure any OpenAI-compatible API below; chat / task generation uses it.",
        ["settings.copilotOpen"] = "Open Copilot",
        ["settings.model"] = "Model",
        ["settings.apiKey"] = "API Key (encrypted with DPAPI)",
        ["settings.baseUrl"] = "Base URL",
        ["settings.modelId"] = "Model name",
        ["settings.backup"] = "Backup / Restore",
        ["settings.export"] = "Export to JSON file",
        ["settings.import"] = "Import from JSON file",
        ["settings.importConfirm"] = "Import will merge into the current database (existing goals are overwritten by Id). Continue?",
        ["settings.documents"] = "Attachment parsing",
        ["settings.documentsHint"] = "Supports .txt / .md / Markdown / .docx; .pdf requires a third-party library and is not built in.",

        ["ai.title"] = "AI Assistant",
        ["ai.hint"] = "Describe what you want to plan, or attach a document to extract tasks. AI returns JSON: when generate=true, the task tree is written into the current goal.",
        ["ai.input"] = "Type a message…",
        ["ai.send"] = "Send",
        ["ai.attach"] = "Attach",
        ["ai.clear"] = "Clear chat",
        ["ai.noAttachText"] = "Cannot parse this attachment (only .txt/.md/.docx supported).",
        ["ai.notConfigured"] = "API Key not configured. Go to Settings → AI Model to set it.",
        ["ai.sending"] = "Thinking…",
        ["ai.generated"] = "Generated tasks written into the current goal.",
        ["ai.history"] = "History",
        ["ai.noHistory"] = "No history yet",

        ["tasks.remaining"] = "Remaining",
        ["tasks.aiImport"] = "AI Import",
        ["tasks.deleteNoSub"] = "Delete task \"{0}\"?",
        ["task.repeat"] = "Repeat",
        ["task.invalidNumber"] = "Please enter a valid number",
        ["task.reminderDate"] = "Reminder date",
        ["task.reminderTime"] = "Reminder time",
        ["ai.newChat"] = "New Chat",
        ["ai.welcome"] = "Hi! I'm your task planner. Describe what you want to plan, or attach a document and I'll turn it into a task list.",
        ["ai.deleteSession"] = "Delete this conversation?",
        ["settings.saved"] = "Settings saved",
        ["settings.exportOk"] = "Backup file exported",
        ["settings.importOk"] = "Import complete: {0} goals restored",

        // ---- Extensions: counting mode / colors / model names / validation / notifications / documents / AI errors / countdown ----
        ["task.counting.header"] = "Counting mode",
        ["task.counting.all"] = "All tasks",
        ["task.counting.leaf"] = "Leaf tasks only",

        ["color.black"] = "Black",
        ["color.red"] = "Red",
        ["color.orange"] = "Orange",
        ["color.yellow"] = "Yellow",
        ["color.green"] = "Green",
        ["color.mint"] = "Mint green",
        ["color.teal"] = "Teal",
        ["color.blue"] = "Blue",
        ["color.indigo"] = "Indigo",
        ["color.purple"] = "Purple",
        ["color.pink"] = "Pink",
        ["color.brown"] = "Brown",

        ["ai.model.qwen"] = "Qwen",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "Yuanbao",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "ERNIE",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "StepFun",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "Custom",

        ["validation.goal.nameEmpty"] = "Goal name cannot be empty",
        ["validation.task.nameEmpty"] = "Task name cannot be empty",

        ["toast.goalPrefix"] = "Goal: {0}",
        ["backup.invalid"] = "Invalid backup file format",

        ["doc.unsupportedDoc"] = "Legacy .doc is not supported. Save as .docx and try again.",
        ["doc.pdfDisabled"] = "PDF attachments are not enabled yet (a text extraction library is required).",
        ["doc.unsupportedType"] = "Unsupported file type. Please use a text or Markdown document.",
        ["doc.noText"] = "No text could be read from the document.",
        ["doc.invalidWord"] = "Could not parse this Word document.",

        ["ai.error.noApiKey"] = "Enter this model's API Key in Settings → AI Model first.",
        ["ai.error.customBaseUrl"] = "Custom models require a Base URL in Settings.",
        ["ai.error.emptyInput"] = "Please enter some content first.",
        ["ai.error.invalidUrl"] = "Invalid model service address.",
        ["ai.error.httpError"] = "Model service returned an error: HTTP {0}",
        ["ai.error.badResponse"] = "Model service returned an invalid response.",
        ["ai.generatedCount"] = "Generated {0} task(s) for you.",
        ["tasks.aiImportPrompt"] = "Generate a task list based on the attachment content",

        ["countdown.yearMonth"] = "{0}y {1}mo",
        ["countdown.year"] = "{0}y",
        ["countdown.monthDay"] = "{0}mo {1}d",
        ["countdown.month"] = "{0}mo",
        ["countdown.dayHour"] = "{0}d {1}h",
        ["countdown.day"] = "{0}d",
        ["countdown.hour"] = "{0}h",
    };

    private static readonly Dictionary<string, string> Fr = new()
    {
        ["app.title"] = "Tick Tâches",
        ["nav.goals"] = "Objectifs",
        ["nav.ai"] = "Assistant IA",
        ["nav.settings"] = "Réglages",

        ["goals.add"] = "Nouvel objectif",
        ["goals.edit"] = "Modifier l'objectif",
        ["goals.delete"] = "Supprimer l'objectif",
        ["goals.deleteConfirm"] = "Supprimer l'objectif \"{0}\" ? Toutes ses tâches seront supprimées.",
        ["goals.empty"] = "Aucun objectif pour l'instant. Appuyez sur « Nouvel objectif » ci-dessous pour en créer un.",

        ["tasks.title"] = "Tâches",
        ["tasks.progress"] = "Progression globale",
        ["tasks.completed"] = "Terminés {0}/{1}",
        ["tasks.countdown"] = "Compte à rebours",
        ["tasks.add"] = "Ajouter une tâche",
        ["tasks.addSubtask"] = "Ajouter une sous-tâche",
        ["tasks.edit"] = "Modifier la tâche",
        ["tasks.delete"] = "Supprimer la tâche",
        ["tasks.deleteConfirm"] = "Supprimer la tâche \"{0}\" ? Toutes ses sous-tâches seront supprimées.",
        ["tasks.noEndDate"] = "Aucune date d'échéance",

        ["task.name"] = "Nom",
        ["task.type"] = "Type",
        ["task.single"] = "Ponctuel",
        ["task.progress"] = "Progression",
        ["task.status"] = "Statut",
        ["task.notDone"] = "Non terminé",
        ["task.halfDone"] = "Partiellement terminé",
        ["task.done"] = "Terminé",
        ["task.deleted"] = "Supprimé",
        ["task.total"] = "Quantité totale",
        ["task.current"] = "Actuel",
        ["task.color"] = "Couleur",
        ["task.color.auto"] = "Auto",
        ["task.startDate"] = "Date de début",
        ["task.endDate"] = "Date d'échéance",
        ["task.preciseToHour"] = "Précis à l'heure",
        ["task.reminder"] = "Rappel",
        ["task.inherited"] = "（hérité du parent）",
        ["task.takenOver"] = "（repris par les sous-tâches）",

        ["repeat.never"] = "Jamais",
        ["repeat.daily"] = "Quotidien",
        ["repeat.weekly"] = "Hebdomadaire",
        ["repeat.monthly"] = "Mensuel",
        ["repeat.custom"] = "Personnalisé",
        ["weekday.1"] = "Dimanche",
        ["weekday.2"] = "Lundi",
        ["weekday.3"] = "Mardi",
        ["weekday.4"] = "Mercredi",
        ["weekday.5"] = "Jeudi",
        ["weekday.6"] = "Vendredi",
        ["weekday.7"] = "Samedi",

        ["common.cancel"] = "Annuler",
        ["common.ok"] = "OK",
        ["common.save"] = "Enregistrer",
        ["common.name"] = "Nom",
        ["common.error"] = "Erreur",
        ["common.notice"] = "Info",
        ["common.warning"] = "Avertissement",

        ["settings.title"] = "Réglages",
        ["settings.theme"] = "Nuancier",
        ["theme.system"] = "Suivre le système",
        ["theme.light"] = "Clair",
        ["theme.dark"] = "Sombre",
        ["settings.language"] = "Langue",
        ["lang.system"] = "Suivre le système",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "Configuration IA",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows ne dispose d'aucune API publique tierce de grand modèle local ; aucune IA n'est donc intégrée. Configurez ci-dessous la clé API d'un modèle compatible OpenAI : la conversation / la génération de tâches passeront par cette interface.",
        ["settings.copilotOpen"] = "Ouvrir Copilot",
        ["settings.model"] = "Modèle",
        ["settings.apiKey"] = "Clé API (stockée chiffrée avec DPAPI)",
        ["settings.baseUrl"] = "URL de base",
        ["settings.modelId"] = "Nom du modèle",
        ["settings.backup"] = "Sauvegarde / Restauration",
        ["settings.export"] = "Exporter vers un fichier JSON",
        ["settings.import"] = "Importer depuis un fichier JSON",
        ["settings.importConfirm"] = "L'importation fusionnera la base actuelle (les objectifs existants sont écrasés par Id). Continuer ?",
        ["settings.documents"] = "Analyse des pièces jointes",
        ["settings.documentsHint"] = "Prend en charge .txt / .md / Markdown / .docx ; le .pdf nécessite une bibliothèque tierce et n'est pas inclus dans cette version.",

        ["ai.title"] = "Assistant IA",
        ["ai.hint"] = "Décrivez ce que vous voulez planifier ou joignez un document pour que l'IA en extraie des tâches. L'IA renvoie du JSON : lorsque generate=true, l'arborescence des tâches est écrite dans l'objectif courant.",
        ["ai.input"] = "Saisissez un message…",
        ["ai.send"] = "Envoyer",
        ["ai.attach"] = "Joindre",
        ["ai.clear"] = "Effacer la conversation",
        ["ai.noAttachText"] = "Impossible d'analyser cette pièce jointe (seuls .txt/.md/.docx sont pris en charge)",
        ["ai.notConfigured"] = "Aucune clé API configurée. Renseignez-la dans Réglages → Modèle IA.",
        ["ai.sending"] = "Réflexion en cours…",
        ["ai.generated"] = "Les tâches générées ont été écrites dans l'objectif courant.",
        ["ai.history"] = "Historique",
        ["ai.noHistory"] = "Aucun historique",

        ["tasks.remaining"] = "Temps restant",
        ["tasks.aiImport"] = "Import IA",
        ["tasks.deleteNoSub"] = "Supprimer la tâche \"{0}\" ?",
        ["task.repeat"] = "Répéter",
        ["task.invalidNumber"] = "Veuillez saisir un nombre valide",
        ["task.reminderDate"] = "Date du rappel",
        ["task.reminderTime"] = "Heure du rappel",
        ["ai.newChat"] = "Nouvelle conversation",
        ["ai.welcome"] = "Bonjour ! Je suis votre assistant de planification de tâches. Décrivez ce que vous voulez planifier, ou joignez un document pour que je le transforme en liste de tâches.",
        ["ai.deleteSession"] = "Supprimer cette conversation ?",
        ["settings.saved"] = "Réglages enregistrés",
        ["settings.exportOk"] = "Fichier de sauvegarde exporté",
        ["settings.importOk"] = "Import terminé : {0} objectifs restaurés",

        // ---- Extensions : mode de comptage / couleurs / modèles / validation / notifications / documents / erreurs IA / compte à rebours ----
        ["task.counting.header"] = "Mode de comptage",
        ["task.counting.all"] = "Toutes les tâches",
        ["task.counting.leaf"] = "Tâches feuilles uniquement",

        ["color.black"] = "Noir",
        ["color.red"] = "Rouge",
        ["color.orange"] = "Orange",
        ["color.yellow"] = "Jaune",
        ["color.green"] = "Vert",
        ["color.mint"] = "Vert menthe",
        ["color.teal"] = "Cyan",
        ["color.blue"] = "Bleu",
        ["color.indigo"] = "Indigo",
        ["color.purple"] = "Violet",
        ["color.pink"] = "Rose",
        ["color.brown"] = "Marron",

        ["ai.model.qwen"] = "Qwen",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "Yuanbao",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "ERNIE",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "StepFun",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "Personnalisé",

        ["validation.goal.nameEmpty"] = "Le nom de l'objectif ne peut pas être vide",
        ["validation.task.nameEmpty"] = "Le nom de la tâche ne peut pas être vide",

        ["toast.goalPrefix"] = "Objectif : {0}",
        ["backup.invalid"] = "Format de fichier de sauvegarde invalide",

        ["doc.unsupportedDoc"] = "L'ancien format .doc n'est pas pris en charge. Enregistrez au format .docx puis réessayez.",
        ["doc.pdfDisabled"] = "Les pièces jointes PDF ne sont pas encore activées (bibliothèque d'extraction de texte requise).",
        ["doc.unsupportedType"] = "Type de fichier non pris en charge. Utilisez un document texte ou Markdown.",
        ["doc.noText"] = "Aucun texte n'a pu être lu dans le document.",
        ["doc.invalidWord"] = "Impossible d'analyser ce document Word.",

        ["ai.error.noApiKey"] = "Saisissez d'abord la clé API de ce modèle dans Réglages → Modèle IA.",
        ["ai.error.customBaseUrl"] = "Les modèles personnalisés nécessitent une URL de base dans les Réglages.",
        ["ai.error.emptyInput"] = "Veuillez d'abord saisir du contenu.",
        ["ai.error.invalidUrl"] = "Adresse du service de modèle invalide.",
        ["ai.error.httpError"] = "Le service du modèle a renvoyé une erreur : HTTP {0}",
        ["ai.error.badResponse"] = "Le service du modèle a renvoyé une réponse invalide.",
        ["ai.generatedCount"] = "{0} tâche(s) générée(s) pour vous.",
        ["tasks.aiImportPrompt"] = "Génère une liste de tâches à partir du contenu de la pièce jointe",

        ["countdown.yearMonth"] = "{0} an {1} mois",
        ["countdown.year"] = "{0} an",
        ["countdown.monthDay"] = "{0} mois {1} j",
        ["countdown.month"] = "{0} mois",
        ["countdown.dayHour"] = "{0} j {1} h",
        ["countdown.day"] = "{0} j",
        ["countdown.hour"] = "{0} h",
    };

    private static readonly Dictionary<string, string> De = new()
    {
        ["app.title"] = "Tick To-Do",
        ["nav.goals"] = "Ziele",
        ["nav.ai"] = "KI-Assistent",
        ["nav.settings"] = "Einstellungen",

        ["goals.add"] = "Neues Ziel",
        ["goals.edit"] = "Ziel bearbeiten",
        ["goals.delete"] = "Ziel löschen",
        ["goals.deleteConfirm"] = "Ziel \"{0}\" löschen? Alle zugehörigen Aufgaben werden entfernt.",
        ["goals.empty"] = "Noch keine Ziele. Tippen Sie unten auf „Neues Ziel“, um eines zu erstellen.",

        ["tasks.title"] = "Aufgaben",
        ["tasks.progress"] = "Gesamtfortschritt",
        ["tasks.completed"] = "Erledigt {0}/{1}",
        ["tasks.countdown"] = "Countdown",
        ["tasks.add"] = "Aufgabe hinzufügen",
        ["tasks.addSubtask"] = "Unteraufgabe hinzufügen",
        ["tasks.edit"] = "Aufgabe bearbeiten",
        ["tasks.delete"] = "Aufgabe löschen",
        ["tasks.deleteConfirm"] = "Aufgabe \"{0}\" löschen? Alle zugehörigen Unteraufgaben werden entfernt.",
        ["tasks.noEndDate"] = "Kein Fälligkeitsdatum",

        ["task.name"] = "Name",
        ["task.type"] = "Typ",
        ["task.single"] = "Einmalig",
        ["task.progress"] = "Fortschritt",
        ["task.status"] = "Status",
        ["task.notDone"] = "Nicht erledigt",
        ["task.halfDone"] = "Teilweise erledigt",
        ["task.done"] = "Erledigt",
        ["task.deleted"] = "Gelöscht",
        ["task.total"] = "Gesamtmenge",
        ["task.current"] = "Aktuell",
        ["task.color"] = "Farbe",
        ["task.color.auto"] = "Auto",
        ["task.startDate"] = "Startdatum",
        ["task.endDate"] = "Fälligkeitsdatum",
        ["task.preciseToHour"] = "Auf die Stunde genau",
        ["task.reminder"] = "Erinnerung",
        ["task.inherited"] = "（vom übergeordneten ererbt）",
        ["task.takenOver"] = "（von Unteraufgaben übernommen）",

        ["repeat.never"] = "Nie",
        ["repeat.daily"] = "Täglich",
        ["repeat.weekly"] = "Wöchentlich",
        ["repeat.monthly"] = "Monatlich",
        ["repeat.custom"] = "Benutzerdefiniert",
        ["weekday.1"] = "Sonntag",
        ["weekday.2"] = "Montag",
        ["weekday.3"] = "Dienstag",
        ["weekday.4"] = "Mittwoch",
        ["weekday.5"] = "Donnerstag",
        ["weekday.6"] = "Freitag",
        ["weekday.7"] = "Samstag",

        ["common.cancel"] = "Abbrechen",
        ["common.ok"] = "OK",
        ["common.save"] = "Speichern",
        ["common.name"] = "Name",
        ["common.error"] = "Fehler",
        ["common.notice"] = "Hinweis",
        ["common.warning"] = "Warnung",

        ["settings.title"] = "Einstellungen",
        ["settings.theme"] = "Farbschema",
        ["theme.system"] = "System folgen",
        ["theme.light"] = "Hell",
        ["theme.dark"] = "Dunkel",
        ["settings.language"] = "Sprache",
        ["lang.system"] = "System folgen",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "KI-Konfiguration",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows bietet keine öffentliche API für lokale Drittanbieter-LLMs, daher ist keine KI eingebettet. Konfigurieren Sie unten den API-Schlüssel eines beliebigen OpenAI-kompatiblen Modells; Chat/Task-Generierung nutzen diese Schnittstelle.",
        ["settings.copilotOpen"] = "Copilot öffnen",
        ["settings.model"] = "Modell",
        ["settings.apiKey"] = "API-Schlüssel (mit DPAPI verschlüsselt gespeichert)",
        ["settings.baseUrl"] = "Basis-URL",
        ["settings.modelId"] = "Modellname",
        ["settings.backup"] = "Sicherung / Wiederherstellung",
        ["settings.export"] = "Als JSON-Datei exportieren",
        ["settings.import"] = "Aus JSON-Datei importieren",
        ["settings.importConfirm"] = "Beim Import wird die aktuelle Datenbank zusammengeführt (vorhandene Ziele werden per Id überschrieben). Fortfahren?",
        ["settings.documents"] = "Anhang-Analyse",
        ["settings.documentsHint"] = "Unterstützt .txt / .md / Markdown / .docx; .pdf erfordert eine Drittanbieter-Bibliothek und ist in dieser Version nicht enthalten.",

        ["ai.title"] = "KI-Assistent",
        ["ai.hint"] = "Beschreiben Sie, was Sie planen möchten, oder laden Sie einen Anhang hoch, damit die KI Aufgaben extrahiert. Die KI gibt JSON aus: bei generate=true wird der Aufgabenbaum direkt in das aktuelle Ziel geschrieben.",
        ["ai.input"] = "Nachricht eingeben…",
        ["ai.send"] = "Senden",
        ["ai.attach"] = "Anhang",
        ["ai.clear"] = "Chat leeren",
        ["ai.noAttachText"] = "Dieser Anhang kann nicht analysiert werden (nur .txt/.md/.docx unterstützt)",
        ["ai.notConfigured"] = "Kein API-Schlüssel konfiguriert. Bitte unter Einstellungen → KI-Modell festlegen.",
        ["ai.sending"] = "Denke nach…",
        ["ai.generated"] = "Generierte Aufgaben wurden in das aktuelle Ziel geschrieben.",
        ["ai.history"] = "Verlauf",
        ["ai.noHistory"] = "Kein Verlauf",

        ["tasks.remaining"] = "Verbleibende Zeit",
        ["tasks.aiImport"] = "KI-Import",
        ["tasks.deleteNoSub"] = "Aufgabe \"{0}\" löschen?",
        ["task.repeat"] = "Wiederholen",
        ["task.invalidNumber"] = "Bitte eine gültige Zahl eingeben",
        ["task.reminderDate"] = "Erinnerungsdatum",
        ["task.reminderTime"] = "Erinnerungszeit",
        ["ai.newChat"] = "Neuer Chat",
        ["ai.welcome"] = "Hallo! Ich bin Ihr Planungsassistent für Aufgaben. Beschreiben Sie, was Sie planen möchten, oder hängen Sie ein Dokument an, das ich in eine Aufgabenliste verwandle.",
        ["ai.deleteSession"] = "Diesen Verlauf löschen?",
        ["settings.saved"] = "Einstellungen gespeichert",
        ["settings.exportOk"] = "Sicherungsdatei exportiert",
        ["settings.importOk"] = "Import abgeschlossen: {0} Ziele wiederhergestellt",

        // ---- Erweiterungen: Zählmodus / Farben / Modellnamen / Validierung / Hinweise / Dokumente / KI-Fehler / Countdown ----
        ["task.counting.header"] = "Zählmodus",
        ["task.counting.all"] = "Alle Aufgaben",
        ["task.counting.leaf"] = "Nur Blattaufgaben",

        ["color.black"] = "Schwarz",
        ["color.red"] = "Rot",
        ["color.orange"] = "Orange",
        ["color.yellow"] = "Gelb",
        ["color.green"] = "Grün",
        ["color.mint"] = "Minzgrün",
        ["color.teal"] = "Türkis",
        ["color.blue"] = "Blau",
        ["color.indigo"] = "Indigo",
        ["color.purple"] = "Violett",
        ["color.pink"] = "Pink",
        ["color.brown"] = "Braun",

        ["ai.model.qwen"] = "Qwen",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "Yuanbao",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "ERNIE",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "StepFun",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "Benutzerdefiniert",

        ["validation.goal.nameEmpty"] = "Zielname darf nicht leer sein",
        ["validation.task.nameEmpty"] = "Aufgabenname darf nicht leer sein",

        ["toast.goalPrefix"] = "Ziel: {0}",
        ["backup.invalid"] = "Ungültiges Sicherungsdateiformat",

        ["doc.unsupportedDoc"] = "Das alte .doc-Format wird nicht unterstützt. Speichern Sie als .docx und versuchen Sie es erneut.",
        ["doc.pdfDisabled"] = "PDF-Anhänge sind noch nicht aktiviert (Text-Extraktionsbibliothek erforderlich).",
        ["doc.unsupportedType"] = "Nicht unterstützter Dateityp. Bitte ein Text- oder Markdown-Dokument verwenden.",
        ["doc.noText"] = "Aus dem Dokument konnte kein Text gelesen werden.",
        ["doc.invalidWord"] = "Dieses Word-Dokument konnte nicht analysiert werden.",

        ["ai.error.noApiKey"] = "Bitte zuerst den API-Schlüssel dieses Modells unter Einstellungen → KI-Modell eingeben.",
        ["ai.error.customBaseUrl"] = "Für benutzerdefinierte Modelle ist eine Basis-URL in den Einstellungen erforderlich.",
        ["ai.error.emptyInput"] = "Bitte zuerst einen Inhalt eingeben.",
        ["ai.error.invalidUrl"] = "Ungültige Adresse des Modelldienstes.",
        ["ai.error.httpError"] = "Der Modelldienst hat einen Fehler zurückgegeben: HTTP {0}",
        ["ai.error.badResponse"] = "Der Modelldienst hat eine ungültige Antwort zurückgegeben.",
        ["ai.generatedCount"] = "{0} Aufgabe(n) für Sie generiert.",
        ["tasks.aiImportPrompt"] = "Erstelle eine Aufgabenliste basierend auf dem Inhalt des Anhangs",

        ["countdown.yearMonth"] = "{0} J. {1} Mon.",
        ["countdown.year"] = "{0} J.",
        ["countdown.monthDay"] = "{0} Mon. {1} T.",
        ["countdown.month"] = "{0} Mon.",
        ["countdown.dayHour"] = "{0} T. {1} Std.",
        ["countdown.day"] = "{0} T.",
        ["countdown.hour"] = "{0} Std.",
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["app.title"] = "Tick Pendientes",
        ["nav.goals"] = "Objetivos",
        ["nav.ai"] = "Asistente de IA",
        ["nav.settings"] = "Ajustes",

        ["goals.add"] = "Nuevo objetivo",
        ["goals.edit"] = "Editar objetivo",
        ["goals.delete"] = "Eliminar objetivo",
        ["goals.deleteConfirm"] = "¿Eliminar el objetivo \"{0}\"? Se eliminarán todas sus tareas.",
        ["goals.empty"] = "Aún no hay objetivos. Toque «Nuevo objetivo» abajo para crear uno.",

        ["tasks.title"] = "Tareas",
        ["tasks.progress"] = "Progreso general",
        ["tasks.completed"] = "Completadas {0}/{1}",
        ["tasks.countdown"] = "Cuenta atrás",
        ["tasks.add"] = "Añadir tarea",
        ["tasks.addSubtask"] = "Añadir subtarea",
        ["tasks.edit"] = "Editar tarea",
        ["tasks.delete"] = "Eliminar tarea",
        ["tasks.deleteConfirm"] = "¿Eliminar la tarea \"{0}\"? Se eliminarán todas sus subtareas.",
        ["tasks.noEndDate"] = "Sin fecha límite",

        ["task.name"] = "Nombre",
        ["task.type"] = "Tipo",
        ["task.single"] = "Único",
        ["task.progress"] = "Progreso",
        ["task.status"] = "Estado",
        ["task.notDone"] = "Sin hacer",
        ["task.halfDone"] = "A medias",
        ["task.done"] = "Hecho",
        ["task.deleted"] = "Eliminado",
        ["task.total"] = "Cantidad total",
        ["task.current"] = "Actual",
        ["task.color"] = "Color",
        ["task.color.auto"] = "Automático",
        ["task.startDate"] = "Fecha de inicio",
        ["task.endDate"] = "Fecha límite",
        ["task.preciseToHour"] = "Preciso a la hora",
        ["task.reminder"] = "Recordatorio",
        ["task.inherited"] = "（heredado del padre）",
        ["task.takenOver"] = "（asumido por las subtareas）",

        ["repeat.never"] = "Nunca",
        ["repeat.daily"] = "Diario",
        ["repeat.weekly"] = "Semanal",
        ["repeat.monthly"] = "Mensual",
        ["repeat.custom"] = "Personalizado",
        ["weekday.1"] = "Domingo",
        ["weekday.2"] = "Lunes",
        ["weekday.3"] = "Martes",
        ["weekday.4"] = "Miércoles",
        ["weekday.5"] = "Jueves",
        ["weekday.6"] = "Viernes",
        ["weekday.7"] = "Sábado",

        ["common.cancel"] = "Cancelar",
        ["common.ok"] = "Aceptar",
        ["common.save"] = "Guardar",
        ["common.name"] = "Nombre",
        ["common.error"] = "Error",
        ["common.notice"] = "Aviso",
        ["common.warning"] = "Advertencia",

        ["settings.title"] = "Ajustes",
        ["settings.theme"] = "Esquema de color",
        ["theme.system"] = "Seguir el sistema",
        ["theme.light"] = "Claro",
        ["theme.dark"] = "Oscuro",
        ["settings.language"] = "Idioma",
        ["lang.system"] = "Seguir el sistema",
        ["lang.zh"] = "简体中文",
        ["lang.zhHant"] = "繁體中文",
        ["lang.ja"] = "日本語",
        ["lang.ko"] = "한국어",
        ["lang.en"] = "English",
        ["lang.fr"] = "Français",
        ["lang.de"] = "Deutsch",
        ["lang.es"] = "Español",
        ["settings.ai"] = "Configuración de IA",
        ["settings.copilot"] = "Windows Copilot",
        ["settings.copilotHint"] = "Windows no dispone de una API pública de modelos locales de terceros, por lo que no incluye IA. Configure abajo una clave de API de cualquier modelo compatible con OpenAI; el chat / la generación de tareas usarán esa interfaz.",
        ["settings.copilotOpen"] = "Abrir Copilot",
        ["settings.model"] = "Modelo",
        ["settings.apiKey"] = "Clave API (almacenada cifrada con DPAPI)",
        ["settings.baseUrl"] = "URL base",
        ["settings.modelId"] = "Nombre del modelo",
        ["settings.backup"] = "Copia de seguridad / Restaurar",
        ["settings.export"] = "Exportar a archivo JSON",
        ["settings.import"] = "Importar desde archivo JSON",
        ["settings.importConfirm"] = "La importación fusionará la base de datos actual (los objetivos existentes se sobrescriben por Id). ¿Continuar?",
        ["settings.documents"] = "Análisis de adjuntos",
        ["settings.documentsHint"] = "Admite .txt / .md / Markdown / .docx; el .pdf requiere una biblioteca de terceros y no está incluido en esta versión.",

        ["ai.title"] = "Asistente de IA",
        ["ai.hint"] = "Describa lo que quiere planificar o adjunte un documento para que la IA extraiga tareas. La IA devuelve JSON: cuando generate=true, el árbol de tareas se escribe en el objetivo actual.",
        ["ai.input"] = "Escriba un mensaje…",
        ["ai.send"] = "Enviar",
        ["ai.attach"] = "Adjuntar",
        ["ai.clear"] = "Vaciar conversación",
        ["ai.noAttachText"] = "No se puede analizar este adjunto (solo .txt/.md/.docx)",
        ["ai.notConfigured"] = "No hay ninguna clave API configurada. Complétela en Ajustes → Modelo de IA.",
        ["ai.sending"] = "Pensando…",
        ["ai.generated"] = "Las tareas generadas se han escrito en el objetivo actual.",
        ["ai.history"] = "Historial",
        ["ai.noHistory"] = "Sin historial",

        ["tasks.remaining"] = "Tiempo restante",
        ["tasks.aiImport"] = "Importar con IA",
        ["tasks.deleteNoSub"] = "¿Eliminar la tarea \"{0}\"?",
        ["task.repeat"] = "Repetir",
        ["task.invalidNumber"] = "Introduzca un número válido",
        ["task.reminderDate"] = "Fecha del recordatorio",
        ["task.reminderTime"] = "Hora del recordatorio",
        ["ai.newChat"] = "Nuevo chat",
        ["ai.welcome"] = "¡Hola! Soy su asistente de planificación de tareas. Describa lo que quiere planificar o adjunte un documento para que lo convierta en una lista de tareas.",
        ["ai.deleteSession"] = "¿Eliminar esta conversación?",
        ["settings.saved"] = "Ajustes guardados",
        ["settings.exportOk"] = "Archivo de copia de seguridad exportado",
        ["settings.importOk"] = "Importación completada: {0} objetivos restaurados",

        // ---- Extensiones: modo de conteo / colores / nombres de modelos / validación / avisos / documentos / errores de IA / cuenta atrás ----
        ["task.counting.header"] = "Modo de conteo",
        ["task.counting.all"] = "Todas las tareas",
        ["task.counting.leaf"] = "Solo tareas hoja",

        ["color.black"] = "Negro",
        ["color.red"] = "Rojo",
        ["color.orange"] = "Naranja",
        ["color.yellow"] = "Amarillo",
        ["color.green"] = "Verde",
        ["color.mint"] = "Verde menta",
        ["color.teal"] = "Cian",
        ["color.blue"] = "Azul",
        ["color.indigo"] = "Índigo",
        ["color.purple"] = "Morado",
        ["color.pink"] = "Rosa",
        ["color.brown"] = "Marrón",

        ["ai.model.qwen"] = "Qwen",
        ["ai.model.deepseek"] = "DeepSeek",
        ["ai.model.chatgpt"] = "ChatGPT",
        ["ai.model.yuanbao"] = "Yuanbao",
        ["ai.model.glm"] = "GLM",
        ["ai.model.kimi"] = "Kimi",
        ["ai.model.ernie"] = "ERNIE",
        ["ai.model.grok"] = "Grok",
        ["ai.model.stepfun"] = "StepFun",
        ["ai.model.minimax"] = "MiniMax",
        ["ai.model.custom"] = "Personalizado",

        ["validation.goal.nameEmpty"] = "El nombre del objetivo no puede estar vacío",
        ["validation.task.nameEmpty"] = "El nombre de la tarea no puede estar vacío",

        ["toast.goalPrefix"] = "Objetivo: {0}",
        ["backup.invalid"] = "Formato de archivo de copia de seguridad no válido",

        ["doc.unsupportedDoc"] = "El formato .doc antiguo no es compatible. Guárdelo como .docx e inténtelo de nuevo.",
        ["doc.pdfDisabled"] = "Los adjuntos PDF aún no están habilitados (se requiere una biblioteca de extracción de texto).",
        ["doc.unsupportedType"] = "Tipo de archivo no compatible. Use un documento de texto o Markdown.",
        ["doc.noText"] = "No se pudo leer texto del documento.",
        ["doc.invalidWord"] = "No se pudo analizar este documento de Word.",

        ["ai.error.noApiKey"] = "Introduzca primero la clave API de este modelo en Ajustes → Modelo de IA.",
        ["ai.error.customBaseUrl"] = "Los modelos personalizados requieren una URL base en los Ajustes.",
        ["ai.error.emptyInput"] = "Introduzca primero algún contenido.",
        ["ai.error.invalidUrl"] = "Dirección del servicio del modelo no válida.",
        ["ai.error.httpError"] = "El servicio del modelo devolvió un error: HTTP {0}",
        ["ai.error.badResponse"] = "El servicio del modelo devolvió una respuesta no válida.",
        ["ai.generatedCount"] = "Se generaron {0} tarea(s) para usted.",
        ["tasks.aiImportPrompt"] = "Genera una lista de tareas a partir del contenido del adjunto",

        ["countdown.yearMonth"] = "{0} a {1} m",
        ["countdown.year"] = "{0} a",
        ["countdown.monthDay"] = "{0} m {1} d",
        ["countdown.month"] = "{0} m",
        ["countdown.dayHour"] = "{0} d {1} h",
        ["countdown.day"] = "{0} d",
        ["countdown.hour"] = "{0} h",
    };

    /// <summary>语言切换事件（MainWindow 据此重新导航 / 重建界面）</summary>
    public static event System.Action? LanguageChanged;

    /// <summary>
    /// 设置当前语言。"system" 表示跟随系统语言（解析为 8 种之一）。
    /// 合法码：zh / zh-Hant / ja / ko / en / fr / de / es；未知输入回退 "zh"。
    /// </summary>
    public static void SetLanguage(string lang)
    {
        lang = Normalize(lang);
        if (_lang == lang)
            return;
        _lang = lang;
        LanguageChanged?.Invoke();
    }

    public static string Tr(string key)
    {
        var table = CurrentTable();
        if (table.TryGetValue(key, out var v))
            return v;
        return Zh.TryGetValue(key, out var fallback) ? fallback : key;
    }

    /// <summary>归一化语言码；解析「跟随系统」为 8 语言之一。</summary>
    private static string Normalize(string lang)
    {
        if (string.Equals(lang, "system", System.StringComparison.OrdinalIgnoreCase))
            lang = ResolveSystemLanguage();
        return lang.ToLowerInvariant() switch
        {
            "zh" => "zh",
            "zh-hant" or "zh-tw" or "zh-hk" => "zh-Hant",
            "ja" => "ja",
            "ko" => "ko",
            "en" => "en",
            "fr" => "fr",
            "de" => "de",
            "es" => "es",
            _ => "zh",
        };
    }

    private static Dictionary<string, string> CurrentTable() => _lang switch
    {
        "zh-Hant" => ZhHant,
        "ja" => Ja,
        "ko" => Ko,
        "en" => En,
        "fr" => Fr,
        "de" => De,
        "es" => Es,
        _ => Zh,
    };

    /// <summary>按系统首选语言解析出 8 语言码之一（兼容 zh-Hant / zh-TW / zh-HK）。</summary>
    private static string ResolveSystemLanguage()
    {
        try
        {
            var prefs = GlobalizationPreferences.Languages;
            if (prefs is { Count: > 0 })
            {
                var code = prefs[0]?.ToLowerInvariant() ?? "";
                if (code.StartsWith("zh-hant") || code.StartsWith("zh-tw") || code.StartsWith("zh-hk"))
                    return "zh-Hant";
                if (code.StartsWith("zh"))
                    return "zh";
                if (code.StartsWith("ja"))
                    return "ja";
                if (code.StartsWith("ko"))
                    return "ko";
                if (code.StartsWith("fr"))
                    return "fr";
                if (code.StartsWith("de"))
                    return "de";
                if (code.StartsWith("es"))
                    return "es";
                return "en";
            }
        }
        catch
        {
            // 读取系统语言失败时回退英文
        }
        return "en";
    }
}

/// <summary>XAML 静态文本的本地化标记扩展：Text="{local:L Key=...}"</summary>
[Microsoft.UI.Xaml.Markup.MarkupExtensionReturnType(ReturnType = typeof(string))]
public sealed class L : Microsoft.UI.Xaml.Markup.MarkupExtension
{
    public string Key { get; set; } = "";

    protected override object ProvideValue() => Localization.Tr(Key);
}