package com.tick.app.android.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.tick.app.android.model.AppLanguage

/** 应用的轻量本地化字符串（简体中文/繁體中文/日本語/한국어/English/Français/Deutsch/Español）。 */
data class Strings(
    // 通用
    val appName: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val confirm: String,
    val back: String,
    val done: String,
    val add: String,
    val edit: String,
    val settingsMenu: String,
    // 侧边栏 / 目标
    val goals: String,
    val newGoal: String,
    val editGoal: String,
    val goalName: String,
    val goalNameHint: String,
    val color: String,
    val icon: String,
    val startDate: String,
    val endDate: String,
    val progressMode: String,
    val reasonDeleteGoal: String,
    val hanDoneCount: String,
    val countdown: String,
    val totalProgress: String,
    val noGoal: String,
    val noGoalHint: String,
    // 任务
    val newTask: String,
    val addTask: String,
    val addSubtask: String,
    val taskName: String,
    val taskNameHint: String,
    val taskType: String,
    val typeSingle: String,
    val typeProgress: String,
    val status: String,
    val total: String,
    val current: String,
    val reminderTime: String,
    val reminderChannelName: String,
    val repeat: String,
    val reasonDeleteTask: String,
    val reasonDeleteTaskCascade: String,
    val reasonEdit: String,
    val statusNotDone: String,
    val statusHalfDone: String,
    val statusDone: String,
    val statusDeleted: String,
    // 设置
    val settings: String,
    val themeMode: String,
    val colorScheme: String,
    val language: String,
    val skin: String,
    val aiConfig: String,
    val aiBaseUrl: String,
    val aiModelName: String,
    val apiKey: String,
    val apiKeyHint: String,
    val dataBackup: String,
    val exportData: String,
    val importData: String,
    val aiCopilotNote: String,
    // AI 聊天
    val aiChat: String,
    val aiChatHint: String,
    val send: String,
    val attach: String,
    val attaching: String,
    val generating: String,
    val aiError: String,
    // 语言/配色选项
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val langSystem: String,
    val langZh: String,
    val langZhHant: String,
    val langJa: String,
    val langKo: String,
    val langEn: String,
    val langFr: String,
    val langDe: String,
    val langEs: String,
    // 任务行 / 无障碍
    val expand: String,
    val collapse: String,
    val decrease: String,
    val increase: String,
    val set: String,
    val none: String,
    // 进度统计模式
    val countAllTasks: String,
    val countLeafTasks: String,
    // 重复规则 / 星期
    val repeatNever: String,
    val repeatDaily: String,
    val repeatWeekly: String,
    val repeatMonthly: String,
    val repeatCustom: String,
    /** 一周七天短名（索引 0=周日 … 6=周六） */
    val weekdayShort: List<String>,
    // 设置 / 备份
    val failed: String,
    val provider: String,
    // AI 聊天
    val newChat: String,
    val inputMessage: String,
    val attachParseFailed: String,
    val requestFailed: String,
    val received: String,
    val attachmentPrefix: String,
    // 倒计时
    val countdownExpired: String,
    val countdownToday: String,
    /** 形如 "{0}天" */
    val countdownDays: String,
    /** 形如 "{0}天 {1}小时" */
    val countdownDaysHours: String,
    // AI 错误
    val aiErrMissingKey: String,
    val aiErrMissingConfig: String,
    val aiErrNetwork: String,
    val aiErrBadResponse: String,
    val aiErrEmptyResult: String,
    // 模型 / 皮肤
    val modelCustom: String,
    /** 皮肤 id → 本地化颜色名（red/orange/lemon/emerald/azure/lake/lilac） */
    val skinNames: Map<String, String>,
    /** AI 模型 id → 本地化名称（仅列出与品牌原名不同的中文品牌：qwen/yuanbao/ernie/stepfun） */
    val modelNames: Map<String, String>
) {
    companion object {
        val zh = Strings(
            expand = "展开",
            collapse = "收起",
            decrease = "减少",
            increase = "增加",
            set = "设置",
            none = "无",
            countAllTasks = "全部任务",
            countLeafTasks = "仅叶子任务",
            repeatNever = "不重复",
            repeatDaily = "每天",
            repeatWeekly = "每周",
            repeatMonthly = "每月",
            repeatCustom = "自定义",
            weekdayShort = listOf("日", "一", "二", "三", "四", "五", "六"),
            failed = "操作失败",
            provider = "服务商",
            newChat = "新对话",
            inputMessage = "输入消息…",
            attachParseFailed = "附件解析失败",
            requestFailed = "请求失败",
            received = "收到",
            attachmentPrefix = "【附件】",
            countdownExpired = "已截止",
            countdownToday = "今天",
            countdownDays = "{0}天",
            countdownDaysHours = "{0}天 {1}小时",
            aiErrMissingKey = "请先在 设置 → AI 模型 中填写 API Key",
            aiErrMissingConfig = "请填写 Base URL 与模型名后重试",
            aiErrNetwork = "网络请求失败：{0}",
            aiErrBadResponse = "模型服务返回了异常响应：{0}",
            aiErrEmptyResult = "模型未生成有效内容",
            modelCustom = "自定义",
            skinNames = mapOf(
                "red" to "红色", "orange" to "活力橙", "lemon" to "柠檬黄",
                "emerald" to "翡翠绿", "azure" to "蔚蓝", "lake" to "湖蓝", "lilac" to "淡紫"
            ),
            modelNames = emptyMap(),
            appName = "Tick",
            save = "保存",
            cancel = "取消",
            delete = "删除",
            confirm = "确定",
            back = "返回",
            done = "完成",
            add = "添加",
            edit = "编辑",
            settingsMenu = "菜单",
            goals = "目标",
            newGoal = "新建目标",
            editGoal = "编辑目标",
            goalName = "名称",
            goalNameHint = "输入目标名称",
            color = "颜色",
            icon = "图标",
            startDate = "开始日期",
            endDate = "截止日期",
            progressMode = "进度统计",
            reasonDeleteGoal = "删除该目标将同时删除其下全部任务，确定删除？",
            hanDoneCount = "已完成 {0} / {1}",
            countdown = "倒计时",
            totalProgress = "总进度",
            noGoal = "暂无目标",
            noGoalHint = "点击右下角按钮新建一个目标吧",
            newTask = "新建任务",
            addTask = "添加任务",
            addSubtask = "添加子任务",
            taskName = "任务名称",
            taskNameHint = "输入任务名称",
            taskType = "类型",
            typeSingle = "单项",
            typeProgress = "进度",
            status = "状态",
            total = "总量",
            current = "当前",
            reminderTime = "提醒时间",
            reminderChannelName = "任务提醒",
            repeat = "重复",
            reasonDeleteTask = "确定删除该任务？",
            reasonDeleteTaskCascade = "该任务包含子任务，删除将一并删除全部子任务，确定删除？",
            reasonEdit = "编辑任务",
            statusNotDone = "未完成",
            statusHalfDone = "半完成",
            statusDone = "完成",
            statusDeleted = "删除",
            settings = "设置",
            themeMode = "配色",
            colorScheme = "配色方案",
            language = "语言",
            skin = "皮肤",
            aiConfig = "AI 模型",
            aiBaseUrl = "Base URL",
            aiModelName = "模型名",
            apiKey = "API Key",
            apiKeyHint = "填写你的 API Key",
            dataBackup = "数据备份",
            exportData = "导出数据",
            importData = "导入数据",
            aiCopilotNote = "Android 各厂商助手（小爱/Bixby/YOYO 等）无公开 API，故不内嵌。请配置 OpenAI 兼容 API（默认 DeepSeek）即可在 AI 聊天中使用任务生成与对话能力。",
            aiChat = "AI 助手",
            aiChatHint = "描述你想规划的事项，或上传附件让我生成任务清单",
            send = "发送",
            attach = "附件",
            attaching = "正在解析附件…",
            generating = "AI 思考中…",
            aiError = "请求失败，请检查设置在“AI 模型”中的配置与网络",
            themeSystem = "跟随系统",
            themeLight = "亮色",
            themeDark = "暗色",
            langSystem = "跟随系统",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val en = Strings(
            expand = "Expand",
            collapse = "Collapse",
            decrease = "Decrease",
            increase = "Increase",
            set = "Set",
            none = "None",
            countAllTasks = "All tasks",
            countLeafTasks = "Leaf tasks only",
            repeatNever = "Never",
            repeatDaily = "Daily",
            repeatWeekly = "Weekly",
            repeatMonthly = "Monthly",
            repeatCustom = "Custom",
            weekdayShort = listOf("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"),
            failed = "Failed",
            provider = "Provider",
            newChat = "New chat",
            inputMessage = "Type a message…",
            attachParseFailed = "Failed to parse the attachment",
            requestFailed = "Request failed",
            received = "Received",
            attachmentPrefix = "[Attachment]",
            countdownExpired = "Expired",
            countdownToday = "Today",
            countdownDays = "{0}d",
            countdownDaysHours = "{0}d {1}h",
            aiErrMissingKey = "Enter your API Key in Settings → AI Model first.",
            aiErrMissingConfig = "Fill in the Base URL and model name, then retry.",
            aiErrNetwork = "Network request failed: {0}",
            aiErrBadResponse = "The model service returned an invalid response: {0}",
            aiErrEmptyResult = "The model did not generate valid content.",
            modelCustom = "Custom",
            skinNames = mapOf(
                "red" to "Red", "orange" to "Orange", "lemon" to "Lemon",
                "emerald" to "Emerald", "azure" to "Azure", "lake" to "Lake", "lilac" to "Lilac"
            ),
            modelNames = mapOf(
                "qwen" to "Qwen", "yuanbao" to "Yuanbao", "ernie" to "ERNIE", "stepfun" to "StepFun"
            ),
            appName = "Tick",
            save = "Save",
            cancel = "Cancel",
            delete = "Delete",
            confirm = "OK",
            back = "Back",
            done = "Done",
            add = "Add",
            edit = "Edit",
            settingsMenu = "Menu",
            goals = "Goals",
            newGoal = "New Goal",
            editGoal = "Edit Goal",
            goalName = "Name",
            goalNameHint = "Enter goal name",
            color = "Color",
            icon = "Icon",
            startDate = "Start date",
            endDate = "Due date",
            progressMode = "Progress mode",
            reasonDeleteGoal = "Deleting this goal also deletes all its tasks. Delete?",
            hanDoneCount = "{0} / {1} done",
            countdown = "Countdown",
            totalProgress = "Progress",
            noGoal = "No Goals",
            noGoalHint = "Tap the button to create a goal",
            newTask = "New Task",
            addTask = "Add Task",
            addSubtask = "Add Subtask",
            taskName = "Task name",
            taskNameHint = "Enter task name",
            taskType = "Type",
            typeSingle = "Single",
            typeProgress = "Progress",
            status = "Status",
            total = "Total",
            current = "Current",
            reminderTime = "Reminder time",
            reminderChannelName = "Task reminders",
            repeat = "Repeat",
            reasonDeleteTask = "Delete this task?",
            reasonDeleteTaskCascade = "This task has subtasks. Deleting removes them too. Delete?",
            reasonEdit = "Edit Task",
            statusNotDone = "Not done",
            statusHalfDone = "Half done",
            statusDone = "Done",
            statusDeleted = "Deleted",
            settings = "Settings",
            themeMode = "Theme",
            colorScheme = "Color scheme",
            language = "Language",
            skin = "Skin",
            aiConfig = "AI Model",
            aiBaseUrl = "Base URL",
            aiModelName = "Model",
            apiKey = "API Key",
            apiKeyHint = "Enter your API Key",
            dataBackup = "Data Backup",
            exportData = "Export data",
            importData = "Import data",
            aiCopilotNote = "Android assistants (Xiao Ai/Bixby/YOYO, etc.) expose no public API, so none is bundled. Configure an OpenAI-compatible API (DeepSeek by default) to use task generation and chat in the AI assistant.",
            aiChat = "AI Assistant",
            aiChatHint = "Describe what to plan, or attach a file to generate a task list",
            send = "Send",
            attach = "Attach",
            attaching = "Parsing attachment…",
            generating = "AI is thinking…",
            aiError = "Request failed. Check the AI Model settings and your network.",
            themeSystem = "System",
            themeLight = "Light",
            themeDark = "Dark",
            langSystem = "System",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val zhHant = Strings(
            expand = "展開",
            collapse = "收合",
            decrease = "減少",
            increase = "增加",
            set = "設定",
            none = "無",
            countAllTasks = "全部任務",
            countLeafTasks = "僅葉子任務",
            repeatNever = "不重複",
            repeatDaily = "每天",
            repeatWeekly = "每週",
            repeatMonthly = "每月",
            repeatCustom = "自訂",
            weekdayShort = listOf("日", "一", "二", "三", "四", "五", "六"),
            failed = "操作失敗",
            provider = "服務商",
            newChat = "新增對話",
            inputMessage = "輸入訊息…",
            attachParseFailed = "附件解析失敗",
            requestFailed = "請求失敗",
            received = "收到",
            attachmentPrefix = "【附件】",
            countdownExpired = "已截止",
            countdownToday = "今天",
            countdownDays = "{0}天",
            countdownDaysHours = "{0}天 {1}小時",
            aiErrMissingKey = "請先在 設定 → AI 模型 中填寫 API Key",
            aiErrMissingConfig = "請填寫 Base URL 與模型名後重試",
            aiErrNetwork = "網路請求失敗：{0}",
            aiErrBadResponse = "模型服務回傳了異常回應：{0}",
            aiErrEmptyResult = "模型未產生有效內容",
            modelCustom = "自訂",
            skinNames = mapOf(
                "red" to "紅色", "orange" to "活力橙", "lemon" to "檸檬黃",
                "emerald" to "翡翠綠", "azure" to "蔚藍", "lake" to "湖藍", "lilac" to "淡紫"
            ),
            modelNames = mapOf(
                "qwen" to "千問", "yuanbao" to "元寶", "ernie" to "文心", "stepfun" to "階躍星辰"
            ),
            appName = "Tick",
            save = "儲存",
            cancel = "取消",
            delete = "刪除",
            confirm = "確定",
            back = "返回",
            done = "完成",
            add = "添加",
            edit = "編輯",
            settingsMenu = "選單",
            goals = "目標",
            newGoal = "新建目標",
            editGoal = "編輯目標",
            goalName = "名稱",
            goalNameHint = "輸入目標名稱",
            color = "顏色",
            icon = "圖示",
            startDate = "開始日期",
            endDate = "截止日期",
            progressMode = "進度統計",
            reasonDeleteGoal = "刪除該目標將同時刪除其下全部任務，確定刪除？",
            hanDoneCount = "已完成 {0} / {1}",
            countdown = "倒數計時",
            totalProgress = "總進度",
            noGoal = "暫無目標",
            noGoalHint = "點擊右下角按鈕新建一個目標吧",
            newTask = "新任務",
            addTask = "新增任務",
            addSubtask = "新增子任務",
            taskName = "任務名稱",
            taskNameHint = "輸入任務名稱",
            taskType = "類型",
            typeSingle = "單項",
            typeProgress = "進度",
            status = "狀態",
            total = "總量",
            current = "目前",
            reminderTime = "提醒時間",
            reminderChannelName = "任務提醒",
            repeat = "重複",
            reasonDeleteTask = "確定刪除該任務？",
            reasonDeleteTaskCascade = "該任務包含子任務，刪除將一併刪除全部子任務，確定刪除？",
            reasonEdit = "編輯任務",
            statusNotDone = "未完成",
            statusHalfDone = "半完成",
            statusDone = "完成",
            statusDeleted = "刪除",
            settings = "設定",
            themeMode = "配色",
            colorScheme = "配色方案",
            language = "語言",
            skin = "皮膚",
            aiConfig = "AI 模型",
            aiBaseUrl = "Base URL",
            aiModelName = "模型名",
            apiKey = "API Key",
            apiKeyHint = "填寫你的 API Key",
            dataBackup = "資料備份",
            exportData = "匯出資料",
            importData = "匯入資料",
            aiCopilotNote = "Android 各廠商助手（小愛/Bixby/YOYO 等）無公開 API，故不內嵌。請設定 OpenAI 相容 API（預設 DeepSeek）即可在 AI 聊天中使用任務生成與對話能力。",
            aiChat = "AI 助手",
            aiChatHint = "描述你想規劃的事項，或上傳附件讓我生成任務清單",
            send = "傳送",
            attach = "附件",
            attaching = "正在解析附件…",
            generating = "AI 思考中…",
            aiError = "請求失敗，請檢查「AI 模型」設定中的組態與網路",
            themeSystem = "跟隨系統",
            themeLight = "亮色",
            themeDark = "暗色",
            langSystem = "跟隨系統",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val ja = Strings(
            expand = "展開",
            collapse = "折りたたむ",
            decrease = "減らす",
            increase = "増やす",
            set = "設定",
            none = "なし",
            countAllTasks = "すべてのタスク",
            countLeafTasks = "末端タスクのみ",
            repeatNever = "繰り返しなし",
            repeatDaily = "毎日",
            repeatWeekly = "毎週",
            repeatMonthly = "毎月",
            repeatCustom = "カスタム",
            weekdayShort = listOf("日", "月", "火", "水", "木", "金", "土"),
            failed = "失敗しました",
            provider = "プロバイダー",
            newChat = "新しいチャット",
            inputMessage = "メッセージを入力…",
            attachParseFailed = "添付ファイルの解析に失敗しました",
            requestFailed = "リクエストに失敗しました",
            received = "受信しました",
            attachmentPrefix = "【添付】",
            countdownExpired = "期限切れ",
            countdownToday = "今日",
            countdownDays = "{0}日",
            countdownDaysHours = "{0}日 {1}時間",
            aiErrMissingKey = "先に 設定 → AI モデル で API Key を入力してください。",
            aiErrMissingConfig = "Base URL とモデル名を入力して再試行してください。",
            aiErrNetwork = "ネットワークリクエストに失敗しました：{0}",
            aiErrBadResponse = "モデルサービスが異常な応答を返しました：{0}",
            aiErrEmptyResult = "モデルが有効な内容を生成しませんでした。",
            modelCustom = "カスタム",
            skinNames = mapOf(
                "red" to "レッド", "orange" to "オレンジ", "lemon" to "レモン",
                "emerald" to "エメラルド", "azure" to "アジュール", "lake" to "レイク", "lilac" to "ライラック"
            ),
            modelNames = mapOf(
                "qwen" to "Qwen", "yuanbao" to "Yuanbao", "ernie" to "ERNIE", "stepfun" to "StepFun"
            ),
            appName = "Tick",
            save = "保存",
            cancel = "キャンセル",
            delete = "削除",
            confirm = "OK",
            back = "戻る",
            done = "完了",
            add = "追加",
            edit = "編集",
            settingsMenu = "メニュー",
            goals = "目標",
            newGoal = "新規目標",
            editGoal = "目標を編集",
            goalName = "名前",
            goalNameHint = "目標名を入力",
            color = "カラー",
            icon = "アイコン",
            startDate = "開始日",
            endDate = "期限日",
            progressMode = "進度の集計",
            reasonDeleteGoal = "この目標を削除すると配下のすべてのタスクも削除されます。削除しますか？",
            hanDoneCount = "{0} / {1} 件完了",
            countdown = "カウントダウン",
            totalProgress = "全体の進捗",
            noGoal = "目標がありません",
            noGoalHint = "右下のボタンをタップして目標を作成しましょう",
            newTask = "新規タスク",
            addTask = "タスクを追加",
            addSubtask = "サブタスクを追加",
            taskName = "タスク名",
            taskNameHint = "タスク名を入力",
            taskType = "種類",
            typeSingle = "単項目",
            typeProgress = "進捗",
            status = "ステータス",
            total = "合計量",
            current = "現在",
            reminderTime = "リマインダー時刻",
            reminderChannelName = "タスクのリマインダー",
            repeat = "繰り返し",
            reasonDeleteTask = "このタスクを削除しますか？",
            reasonDeleteTaskCascade = "このタスクにはサブタスクが含まれています。削除するとすべてのサブタスクも削除されます。削除しますか？",
            reasonEdit = "タスクを編集",
            statusNotDone = "未完了",
            statusHalfDone = "半完了",
            statusDone = "完了",
            statusDeleted = "削除",
            settings = "設定",
            themeMode = "テーマ",
            colorScheme = "カラーテーマ",
            language = "言語",
            skin = "スキン",
            aiConfig = "AI モデル",
            aiBaseUrl = "Base URL",
            aiModelName = "モデル名",
            apiKey = "API Key",
            apiKeyHint = "API Key を入力してください",
            dataBackup = "データバックアップ",
            exportData = "データを書き出す",
            importData = "データを読み込む",
            aiCopilotNote = "Android 各メーカーのアシスタント（小愛/Bixby/YOYO など）は公開 API がないため、組み込んでいません。OpenAI 互換 API（デフォルトは DeepSeek）を設定すれば、AI チャットでタスク生成と会話機能を利用できます。",
            aiChat = "AI アシスタント",
            aiChatHint = "計画したい内容を説明するか、添付ファイルをアップロードしてタスクリストを生成させてください",
            send = "送信",
            attach = "添付",
            attaching = "添付ファイルを解析中…",
            generating = "AI 思考中…",
            aiError = "リクエストに失敗しました。「AI モデル」設定の構成とネットワークを確認してください",
            themeSystem = "システムに従う",
            themeLight = "ライト",
            themeDark = "ダーク",
            langSystem = "システムに従う",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val ko = Strings(
            expand = "펼치기",
            collapse = "접기",
            decrease = "줄이기",
            increase = "늘리기",
            set = "설정",
            none = "없음",
            countAllTasks = "모든 작업",
            countLeafTasks = "말단 작업만",
            repeatNever = "반복 없음",
            repeatDaily = "매일",
            repeatWeekly = "매주",
            repeatMonthly = "매월",
            repeatCustom = "사용자 지정",
            weekdayShort = listOf("일", "월", "화", "수", "목", "금", "토"),
            failed = "실패했습니다",
            provider = "공급자",
            newChat = "새 채팅",
            inputMessage = "메시지 입력…",
            attachParseFailed = "첨부 파일 분석에 실패했습니다",
            requestFailed = "요청 실패",
            received = "수신됨",
            attachmentPrefix = "[첨부]",
            countdownExpired = "기한 지남",
            countdownToday = "오늘",
            countdownDays = "{0}일",
            countdownDaysHours = "{0}일 {1}시간",
            aiErrMissingKey = "먼저 설정 → AI 모델에서 API Key를 입력하세요.",
            aiErrMissingConfig = "Base URL과 모델 이름을 입력한 후 다시 시도하세요.",
            aiErrNetwork = "네트워크 요청 실패: {0}",
            aiErrBadResponse = "모델 서비스가 비정상 응답을 반환했습니다: {0}",
            aiErrEmptyResult = "모델이 유효한 내용을 생성하지 않았습니다.",
            modelCustom = "사용자 지정",
            skinNames = mapOf(
                "red" to "레드", "orange" to "오렌지", "lemon" to "레몬",
                "emerald" to "에메랄드", "azure" to "애저", "lake" to "레이크", "lilac" to "라일락"
            ),
            modelNames = mapOf(
                "qwen" to "Qwen", "yuanbao" to "Yuanbao", "ernie" to "ERNIE", "stepfun" to "StepFun"
            ),
            appName = "Tick",
            save = "저장",
            cancel = "취소",
            delete = "삭제",
            confirm = "확인",
            back = "뒤로",
            done = "완료",
            add = "추가",
            edit = "편집",
            settingsMenu = "메뉴",
            goals = "목표",
            newGoal = "새 목표",
            editGoal = "목표 편집",
            goalName = "이름",
            goalNameHint = "목표 이름 입력",
            color = "색상",
            icon = "아이콘",
            startDate = "시작일",
            endDate = "마감일",
            progressMode = "진도 통계",
            reasonDeleteGoal = "이 목표를 삭제하면 하위 모든 작업도 함께 삭제됩니다. 삭제하시겠습니까?",
            hanDoneCount = "{0} / {1}개 완료",
            countdown = "카운트다운",
            totalProgress = "전체 진행률",
            noGoal = "목표 없음",
            noGoalHint = "오른쪽 아래 버튼을 눌러 목표를 만들어 보세요",
            newTask = "새 작업",
            addTask = "작업 추가",
            addSubtask = "하위 작업 추가",
            taskName = "작업 이름",
            taskNameHint = "작업 이름 입력",
            taskType = "유형",
            typeSingle = "단일 항목",
            typeProgress = "진행률",
            status = "상태",
            total = "총량",
            current = "현재",
            reminderTime = "알림 시간",
            reminderChannelName = "작업 알림",
            repeat = "반복",
            reasonDeleteTask = "이 작업을 삭제하시겠습니까?",
            reasonDeleteTaskCascade = "이 작업에는 하위 작업이 포함되어 있습니다. 삭제하면 모든 하위 작업도 함께 삭제됩니다. 삭제하시겠습니까?",
            reasonEdit = "작업 편집",
            statusNotDone = "미완료",
            statusHalfDone = "반 완료",
            statusDone = "완료",
            statusDeleted = "삭제",
            settings = "설정",
            themeMode = "테마",
            colorScheme = "색상 테마",
            language = "언어",
            skin = "스킨",
            aiConfig = "AI 모델",
            aiBaseUrl = "Base URL",
            aiModelName = "모델명",
            apiKey = "API Key",
            apiKeyHint = "API Key를 입력하세요",
            dataBackup = "데이터 백업",
            exportData = "데이터 내보내기",
            importData = "데이터 가져오기",
            aiCopilotNote = "Android 각 제조사 어시스턴트(小愛/Bixby/YOYO 등)에는 공개 API가 없어 내장되어 있지 않습니다. OpenAI 호환 API(기본 DeepSeek)를 설정하면 AI 채팅에서 작업 생성과 대화 기능을 사용할 수 있습니다.",
            aiChat = "AI 어시스턴트",
            aiChatHint = "계획할 내용을 설명하거나 첨부 파일을 업로드하여 작업 목록을 생성하세요",
            send = "보내기",
            attach = "첨부",
            attaching = "첨부 파일을 분석 중…",
            generating = "AI가 생각하는 중…",
            aiError = "요청에 실패했습니다. 'AI 모델' 설정의 구성과 네트워크를 확인하세요",
            themeSystem = "시스템 따르기",
            themeLight = "라이트",
            themeDark = "다크",
            langSystem = "시스템 따르기",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val fr = Strings(
            expand = "Développer",
            collapse = "Réduire",
            decrease = "Diminuer",
            increase = "Augmenter",
            set = "Définir",
            none = "Aucun",
            countAllTasks = "Toutes les tâches",
            countLeafTasks = "Tâches feuilles uniquement",
            repeatNever = "Jamais",
            repeatDaily = "Quotidien",
            repeatWeekly = "Hebdomadaire",
            repeatMonthly = "Mensuel",
            repeatCustom = "Personnalisé",
            weekdayShort = listOf("Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"),
            failed = "Échec",
            provider = "Fournisseur",
            newChat = "Nouvelle conversation",
            inputMessage = "Saisissez un message…",
            attachParseFailed = "Échec de l'analyse de la pièce jointe",
            requestFailed = "Échec de la requête",
            received = "Reçu",
            attachmentPrefix = "[Pièce jointe]",
            countdownExpired = "Expiré",
            countdownToday = "Aujourd'hui",
            countdownDays = "{0} j",
            countdownDaysHours = "{0} j {1} h",
            aiErrMissingKey = "Saisissez d'abord votre clé API dans Réglages → Modèle IA.",
            aiErrMissingConfig = "Renseignez l'URL de base et le nom du modèle, puis réessayez.",
            aiErrNetwork = "Échec de la requête réseau : {0}",
            aiErrBadResponse = "Le service du modèle a renvoyé une réponse invalide : {0}",
            aiErrEmptyResult = "Le modèle n'a généré aucun contenu valide.",
            modelCustom = "Personnalisé",
            skinNames = mapOf(
                "red" to "Rouge", "orange" to "Orange", "lemon" to "Citron",
                "emerald" to "Émeraude", "azure" to "Azur", "lake" to "Lac", "lilac" to "Lilas"
            ),
            modelNames = mapOf(
                "qwen" to "Qwen", "yuanbao" to "Yuanbao", "ernie" to "ERNIE", "stepfun" to "StepFun"
            ),
            appName = "Tick",
            save = "Enregistrer",
            cancel = "Annuler",
            delete = "Supprimer",
            confirm = "OK",
            back = "Retour",
            done = "Terminé",
            add = "Ajouter",
            edit = "Modifier",
            settingsMenu = "Menu",
            goals = "Objectifs",
            newGoal = "Nouvel objectif",
            editGoal = "Modifier l'objectif",
            goalName = "Nom",
            goalNameHint = "Saisissez le nom de l'objectif",
            color = "Couleur",
            icon = "Icône",
            startDate = "Date de début",
            endDate = "Date d'échéance",
            progressMode = "Suivi de la progression",
            reasonDeleteGoal = "Supprimer cet objectif supprime également toutes ses tâches. Supprimer ?",
            hanDoneCount = "{0} / {1} terminé(s)",
            countdown = "Compte à rebours",
            totalProgress = "Progression globale",
            noGoal = "Aucun objectif",
            noGoalHint = "Appuyez sur le bouton pour créer un objectif",
            newTask = "Nouvelle tâche",
            addTask = "Ajouter une tâche",
            addSubtask = "Ajouter une sous-tâche",
            taskName = "Nom de la tâche",
            taskNameHint = "Saisissez le nom de la tâche",
            taskType = "Type",
            typeSingle = "Ponctuel",
            typeProgress = "Progression",
            status = "Statut",
            total = "Quantité totale",
            current = "Actuel",
            reminderTime = "Heure de rappel",
            reminderChannelName = "Rappels de tâches",
            repeat = "Répétition",
            reasonDeleteTask = "Supprimer cette tâche ?",
            reasonDeleteTaskCascade = "Cette tâche contient des sous-tâches. Les supprimer les supprimera toutes. Supprimer ?",
            reasonEdit = "Modifier la tâche",
            statusNotDone = "Non terminé",
            statusHalfDone = "Partiellement terminé",
            statusDone = "Terminé",
            statusDeleted = "Supprimé",
            settings = "Réglages",
            themeMode = "Thème",
            colorScheme = "Nuancier",
            language = "Langue",
            skin = "Skin",
            aiConfig = "Modèle IA",
            aiBaseUrl = "Base URL",
            aiModelName = "Nom du modèle",
            apiKey = "API Key",
            apiKeyHint = "Saisissez votre API Key",
            dataBackup = "Sauvegarde des données",
            exportData = "Exporter les données",
            importData = "Importer des données",
            aiCopilotNote = "Les assistants des fabricants Android (Xiao Ai/Bixby/YOYO, etc.) n'exposent aucune API publique, aucun n'est donc intégré. Configurez une API compatible OpenAI (DeepSeek par défaut) pour utiliser la génération de tâches et la conversation dans l'assistant IA.",
            aiChat = "Assistant IA",
            aiChatHint = "Décrivez ce que vous voulez planifier, ou joignez un fichier pour générer une liste de tâches",
            send = "Envoyer",
            attach = "Pièce jointe",
            attaching = "Analyse de la pièce jointe…",
            generating = "L'IA réfléchit…",
            aiError = "Échec de la requête. Vérifiez la configuration des réglages « Modèle IA » et le réseau.",
            themeSystem = "Suivre le système",
            themeLight = "Clair",
            themeDark = "Sombre",
            langSystem = "Suivre le système",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val de = Strings(
            expand = "Erweitern",
            collapse = "Einklappen",
            decrease = "Verringern",
            increase = "Erhöhen",
            set = "Festlegen",
            none = "Keine",
            countAllTasks = "Alle Aufgaben",
            countLeafTasks = "Nur Blattaufgaben",
            repeatNever = "Nie",
            repeatDaily = "Täglich",
            repeatWeekly = "Wöchentlich",
            repeatMonthly = "Monatlich",
            repeatCustom = "Benutzerdefiniert",
            weekdayShort = listOf("So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"),
            failed = "Fehlgeschlagen",
            provider = "Anbieter",
            newChat = "Neuer Chat",
            inputMessage = "Nachricht eingeben…",
            attachParseFailed = "Anhang konnte nicht analysiert werden",
            requestFailed = "Anfrage fehlgeschlagen",
            received = "Empfangen",
            attachmentPrefix = "[Anhang]",
            countdownExpired = "Abgelaufen",
            countdownToday = "Heute",
            countdownDays = "{0} T",
            countdownDaysHours = "{0} T {1} Std",
            aiErrMissingKey = "Geben Sie zuerst Ihren API-Schlüssel unter Einstellungen → KI-Modell ein.",
            aiErrMissingConfig = "Geben Sie Basis-URL und Modellname ein und versuchen Sie es erneut.",
            aiErrNetwork = "Netzwerkanfrage fehlgeschlagen: {0}",
            aiErrBadResponse = "Der Modelldienst hat eine ungültige Antwort zurückgegeben: {0}",
            aiErrEmptyResult = "Das Modell hat keinen gültigen Inhalt erzeugt.",
            modelCustom = "Benutzerdefiniert",
            skinNames = mapOf(
                "red" to "Rot", "orange" to "Orange", "lemon" to "Zitrone",
                "emerald" to "Smaragd", "azure" to "Azur", "lake" to "See", "lilac" to "Flieder"
            ),
            modelNames = mapOf(
                "qwen" to "Qwen", "yuanbao" to "Yuanbao", "ernie" to "ERNIE", "stepfun" to "StepFun"
            ),
            appName = "Tick",
            save = "Speichern",
            cancel = "Abbrechen",
            delete = "Löschen",
            confirm = "OK",
            back = "Zurück",
            done = "Erledigt",
            add = "Hinzufügen",
            edit = "Bearbeiten",
            settingsMenu = "Menü",
            goals = "Ziele",
            newGoal = "Neues Ziel",
            editGoal = "Ziel bearbeiten",
            goalName = "Name",
            goalNameHint = "Zielnamen eingeben",
            color = "Farbe",
            icon = "Symbol",
            startDate = "Startdatum",
            endDate = "Fälligkeitsdatum",
            progressMode = "Fortschrittsverfolgung",
            reasonDeleteGoal = "Das Löschen dieses Ziels löscht auch alle zugehörigen Aufgaben. Löschen?",
            hanDoneCount = "{0} / {1} erledigt",
            countdown = "Countdown",
            totalProgress = "Gesamtfortschritt",
            noGoal = "Keine Ziele",
            noGoalHint = "Tippen Sie auf die Schaltfläche, um ein Ziel zu erstellen",
            newTask = "Neue Aufgabe",
            addTask = "Aufgabe hinzufügen",
            addSubtask = "Unteraufgabe hinzufügen",
            taskName = "Aufgabenname",
            taskNameHint = "Aufgabennamen eingeben",
            taskType = "Typ",
            typeSingle = "Einmalig",
            typeProgress = "Fortschritt",
            status = "Status",
            total = "Gesamtmenge",
            current = "Aktuell",
            reminderTime = "Erinnerungszeit",
            reminderChannelName = "Aufgabenerinnerungen",
            repeat = "Wiederholung",
            reasonDeleteTask = "Diese Aufgabe löschen?",
            reasonDeleteTaskCascade = "Diese Aufgabe enthält Unteraufgaben. Beim Löschen werden alle mitgelöscht. Löschen?",
            reasonEdit = "Aufgabe bearbeiten",
            statusNotDone = "Nicht erledigt",
            statusHalfDone = "Teilweise erledigt",
            statusDone = "Erledigt",
            statusDeleted = "Gelöscht",
            settings = "Einstellungen",
            themeMode = "Design",
            colorScheme = "Farbschema",
            language = "Sprache",
            skin = "Skin",
            aiConfig = "KI-Modell",
            aiBaseUrl = "Base URL",
            aiModelName = "Modellname",
            apiKey = "API-Key",
            apiKeyHint = "Geben Sie Ihren API-Key ein",
            dataBackup = "Datensicherung",
            exportData = "Daten exportieren",
            importData = "Daten importieren",
            aiCopilotNote = "Die Assistenten der Android-Hersteller (Xiao Ai/Bixby/YOYO usw.) bieten keine öffentliche API, daher ist keiner integriert. Konfigurieren Sie eine OpenAI-kompatible API (standardmäßig DeepSeek), um die Aufgaben-Erstellung und den Chat im KI-Assistenten zu nutzen.",
            aiChat = "KI-Assistent",
            aiChatHint = "Beschreiben Sie, was Sie planen möchten, oder hängen Sie eine Datei an, um eine Aufgabenliste zu erstellen",
            send = "Senden",
            attach = "Anhang",
            attaching = "Anhang wird analysiert…",
            generating = "KI denkt nach…",
            aiError = "Anfrage fehlgeschlagen. Prüfen Sie die Konfiguration in den Einstellungen „KI-Modell“ und das Netzwerk.",
            themeSystem = "System folgen",
            themeLight = "Hell",
            themeDark = "Dunkel",
            langSystem = "System folgen",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val es = Strings(
            expand = "Expandir",
            collapse = "Contraer",
            decrease = "Disminuir",
            increase = "Aumentar",
            set = "Establecer",
            none = "Ninguno",
            countAllTasks = "Todas las tareas",
            countLeafTasks = "Solo tareas hoja",
            repeatNever = "Nunca",
            repeatDaily = "Diario",
            repeatWeekly = "Semanal",
            repeatMonthly = "Mensual",
            repeatCustom = "Personalizado",
            weekdayShort = listOf("Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"),
            failed = "Error",
            provider = "Proveedor",
            newChat = "Nuevo chat",
            inputMessage = "Escriba un mensaje…",
            attachParseFailed = "No se pudo analizar el archivo adjunto",
            requestFailed = "Error en la solicitud",
            received = "Recibido",
            attachmentPrefix = "[Adjunto]",
            countdownExpired = "Vencido",
            countdownToday = "Hoy",
            countdownDays = "{0} d",
            countdownDaysHours = "{0} d {1} h",
            aiErrMissingKey = "Introduzca primero su clave API en Ajustes → Modelo de IA.",
            aiErrMissingConfig = "Rellene la URL base y el nombre del modelo y vuelva a intentarlo.",
            aiErrNetwork = "Error en la solicitud de red: {0}",
            aiErrBadResponse = "El servicio del modelo devolvió una respuesta no válida: {0}",
            aiErrEmptyResult = "El modelo no generó contenido válido.",
            modelCustom = "Personalizado",
            skinNames = mapOf(
                "red" to "Rojo", "orange" to "Naranja", "lemon" to "Limón",
                "emerald" to "Esmeralda", "azure" to "Azul", "lake" to "Lago", "lilac" to "Lila"
            ),
            modelNames = mapOf(
                "qwen" to "Qwen", "yuanbao" to "Yuanbao", "ernie" to "ERNIE", "stepfun" to "StepFun"
            ),
            appName = "Tick",
            save = "Guardar",
            cancel = "Cancelar",
            delete = "Eliminar",
            confirm = "Aceptar",
            back = "Atrás",
            done = "Hecho",
            add = "Añadir",
            edit = "Editar",
            settingsMenu = "Menú",
            goals = "Objetivos",
            newGoal = "Nuevo objetivo",
            editGoal = "Editar objetivo",
            goalName = "Nombre",
            goalNameHint = "Introduzca el nombre del objetivo",
            color = "Color",
            icon = "Icono",
            startDate = "Fecha de inicio",
            endDate = "Fecha límite",
            progressMode = "Seguimiento del progreso",
            reasonDeleteGoal = "Eliminar este objetivo también elimina todas sus tareas. ¿Eliminar?",
            hanDoneCount = "{0} / {1} completadas",
            countdown = "Cuenta atrás",
            totalProgress = "Progreso general",
            noGoal = "Sin objetivos",
            noGoalHint = "Toque el botón para crear un objetivo",
            newTask = "Nueva tarea",
            addTask = "Añadir tarea",
            addSubtask = "Añadir subtarea",
            taskName = "Nombre de la tarea",
            taskNameHint = "Introduzca el nombre de la tarea",
            taskType = "Tipo",
            typeSingle = "Único",
            typeProgress = "Progreso",
            status = "Estado",
            total = "Cantidad total",
            current = "Actual",
            reminderTime = "Hora del recordatorio",
            reminderChannelName = "Recordatorios de tareas",
            repeat = "Repetición",
            reasonDeleteTask = "¿Eliminar esta tarea?",
            reasonDeleteTaskCascade = "Esta tarea contiene subtareas. Eliminarla eliminará todas. ¿Eliminar?",
            reasonEdit = "Editar tarea",
            statusNotDone = "Sin hacer",
            statusHalfDone = "A medias",
            statusDone = "Hecho",
            statusDeleted = "Eliminado",
            settings = "Ajustes",
            themeMode = "Tema",
            colorScheme = "Esquema de color",
            language = "Idioma",
            skin = "Skin",
            aiConfig = "Modelo de IA",
            aiBaseUrl = "Base URL",
            aiModelName = "Nombre del modelo",
            apiKey = "API Key",
            apiKeyHint = "Introduzca su API Key",
            dataBackup = "Copia de seguridad de datos",
            exportData = "Exportar datos",
            importData = "Importar datos",
            aiCopilotNote = "Los asistentes de los fabricantes de Android (Xiao Ai/Bixby/YOYO, etc.) no exponen una API pública, por lo que no se incluye ninguno. Configure una API compatible con OpenAI (DeepSeek por defecto) para usar la generación de tareas y el chat en el asistente de IA.",
            aiChat = "Asistente de IA",
            aiChatHint = "Describa lo que desea planificar o adjunte un archivo para generar una lista de tareas",
            send = "Enviar",
            attach = "Adjunto",
            attaching = "Analizando el archivo adjunto…",
            generating = "La IA está pensando…",
            aiError = "Error en la solicitud. Compruebe la configuración de «Modelo de IA» y la red.",
            themeSystem = "Seguir el sistema",
            themeLight = "Claro",
            themeDark = "Oscuro",
            langSystem = "Seguir el sistema",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        fun of(language: AppLanguage): Strings = when (language) {
            AppLanguage.ZH_HANS -> zh
            AppLanguage.ZH_HANT -> zhHant
            AppLanguage.JA -> ja
            AppLanguage.KO -> ko
            AppLanguage.EN -> en
            AppLanguage.FR -> fr
            AppLanguage.DE -> de
            AppLanguage.ES -> es
            AppLanguage.SYSTEM -> zh
        }
    }
}

/** 提供当前语言的最合适 TextView 统一文本；供全局访问 */
val LocalStrings = staticCompositionLocalOf { Strings.zh }