package com.tick.app.android.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.tick.app.android.model.AppLanguage

/** 应用的轻量本地化字符串（简体中文/繁體中文/日本語/한국어/English/Français/Deutsch/Español）。 */
data class Strings(
    // 通用
    val appName: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val confirm: String,
    val back: String,
    val done: String,
    val add: String,
    val edit: String,
    val settingsMenu: String,
    // 侧边栏 / 目标
    val goals: String,
    val newGoal: String,
    val editGoal: String,
    val goalName: String,
    val goalNameHint: String,
    val color: String,
    val icon: String,
    val startDate: String,
    val endDate: String,
    val progressMode: String,
    val reasonDeleteGoal: String,
    val hanDoneCount: String,
    val countdown: String,
    val totalProgress: String,
    val noGoal: String,
    val noGoalHint: String,
    // 任务
    val newTask: String,
    val addTask: String,
    val addSubtask: String,
    val taskName: String,
    val taskNameHint: String,
    val taskType: String,
    val typeSingle: String,
    val typeProgress: String,
    val status: String,
    val total: String,
    val current: String,
    val reminderTime: String,
    val repeat: String,
    val reasonDeleteTask: String,
    val reasonDeleteTaskCascade: String,
    val reasonEdit: String,
    val statusNotDone: String,
    val statusHalfDone: String,
    val statusDone: String,
    val statusDeleted: String,
    // 设置
    val settings: String,
    val themeMode: String,
    val colorScheme: String,
    val language: String,
    val skin: String,
    val aiConfig: String,
    val aiBaseUrl: String,
    val aiModelName: String,
    val apiKey: String,
    val apiKeyHint: String,
    val dataBackup: String,
    val exportData: String,
    val importData: String,
    val aiCopilotNote: String,
    // AI 聊天
    val aiChat: String,
    val aiChatHint: String,
    val send: String,
    val attach: String,
    val attaching: String,
    val generating: String,
    val aiError: String,
    // 语言/配色选项
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val langSystem: String,
    val langZh: String,
    val langZhHant: String,
    val langJa: String,
    val langKo: String,
    val langEn: String,
    val langFr: String,
    val langDe: String,
    val langEs: String
) {
    companion object {
        val zh = Strings(
            appName = "Tick",
            save = "保存",
            cancel = "取消",
            delete = "删除",
            confirm = "确定",
            back = "返回",
            done = "完成",
            add = "添加",
            edit = "编辑",
            settingsMenu = "菜单",
            goals = "目标",
            newGoal = "新建目标",
            editGoal = "编辑目标",
            goalName = "名称",
            goalNameHint = "输入目标名称",
            color = "颜色",
            icon = "图标",
            startDate = "开始日期",
            endDate = "截止日期",
            progressMode = "进度统计",
            reasonDeleteGoal = "删除该目标将同时删除其下全部任务，确定删除？",
            hanDoneCount = "已完成 {0} / {1}",
            countdown = "倒计时",
            totalProgress = "总进度",
            noGoal = "暂无目标",
            noGoalHint = "点击右下角按钮新建一个目标吧",
            newTask = "新建任务",
            addTask = "添加任务",
            addSubtask = "添加子任务",
            taskName = "任务名称",
            taskNameHint = "输入任务名称",
            taskType = "类型",
            typeSingle = "单项",
            typeProgress = "进度",
            status = "状态",
            total = "总量",
            current = "当前",
            reminderTime = "提醒时间",
            repeat = "重复",
            reasonDeleteTask = "确定删除该任务？",
            reasonDeleteTaskCascade = "该任务包含子任务，删除将一并删除全部子任务，确定删除？",
            reasonEdit = "编辑任务",
            statusNotDone = "未完成",
            statusHalfDone = "半完成",
            statusDone = "完成",
            statusDeleted = "删除",
            settings = "设置",
            themeMode = "配色",
            colorScheme = "配色方案",
            language = "语言",
            skin = "皮肤",
            aiConfig = "AI 模型",
            aiBaseUrl = "Base URL",
            aiModelName = "模型名",
            apiKey = "API Key",
            apiKeyHint = "填写你的 API Key",
            dataBackup = "数据备份",
            exportData = "导出数据",
            importData = "导入数据",
            aiCopilotNote = "Android 各厂商助手（小爱/Bixby/YOYO 等）无公开 API，故不内嵌。请配置 OpenAI 兼容 API（默认 DeepSeek）即可在 AI 聊天中使用任务生成与对话能力。",
            aiChat = "AI 助手",
            aiChatHint = "描述你想规划的事项，或上传附件让我生成任务清单",
            send = "发送",
            attach = "附件",
            attaching = "正在解析附件…",
            generating = "AI 思考中…",
            aiError = "请求失败，请检查设置在“AI 模型”中的配置与网络",
            themeSystem = "跟随系统",
            themeLight = "亮色",
            themeDark = "暗色",
            langSystem = "跟随系统",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val en = Strings(
            appName = "Tick",
            save = "Save",
            cancel = "Cancel",
            delete = "Delete",
            confirm = "OK",
            back = "Back",
            done = "Done",
            add = "Add",
            edit = "Edit",
            settingsMenu = "Menu",
            goals = "Goals",
            newGoal = "New Goal",
            editGoal = "Edit Goal",
            goalName = "Name",
            goalNameHint = "Enter goal name",
            color = "Color",
            icon = "Icon",
            startDate = "Start date",
            endDate = "Due date",
            progressMode = "Progress mode",
            reasonDeleteGoal = "Deleting this goal also deletes all its tasks. Delete?",
            hanDoneCount = "{0} / {1} done",
            countdown = "Countdown",
            totalProgress = "Progress",
            noGoal = "No Goals",
            noGoalHint = "Tap the button to create a goal",
            newTask = "New Task",
            addTask = "Add Task",
            addSubtask = "Add Subtask",
            taskName = "Task name",
            taskNameHint = "Enter task name",
            taskType = "Type",
            typeSingle = "Single",
            typeProgress = "Progress",
            status = "Status",
            total = "Total",
            current = "Current",
            reminderTime = "Reminder time",
            repeat = "Repeat",
            reasonDeleteTask = "Delete this task?",
            reasonDeleteTaskCascade = "This task has subtasks. Deleting removes them too. Delete?",
            reasonEdit = "Edit Task",
            statusNotDone = "Not done",
            statusHalfDone = "Half done",
            statusDone = "Done",
            statusDeleted = "Deleted",
            settings = "Settings",
            themeMode = "Theme",
            colorScheme = "Color scheme",
            language = "Language",
            skin = "Skin",
            aiConfig = "AI Model",
            aiBaseUrl = "Base URL",
            aiModelName = "Model",
            apiKey = "API Key",
            apiKeyHint = "Enter your API Key",
            dataBackup = "Data Backup",
            exportData = "Export data",
            importData = "Import data",
            aiCopilotNote = "Android assistants (Xiao Ai/Bixby/YOYO, etc.) expose no public API, so none is bundled. Configure an OpenAI-compatible API (DeepSeek by default) to use task generation and chat in the AI assistant.",
            aiChat = "AI Assistant",
            aiChatHint = "Describe what to plan, or attach a file to generate a task list",
            send = "Send",
            attach = "Attach",
            attaching = "Parsing attachment…",
            generating = "AI is thinking…",
            aiError = "Request failed. Check the AI Model settings and your network.",
            themeSystem = "System",
            themeLight = "Light",
            themeDark = "Dark",
            langSystem = "System",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val zhHant = Strings(
            appName = "Tick",
            save = "儲存",
            cancel = "取消",
            delete = "刪除",
            confirm = "確定",
            back = "返回",
            done = "完成",
            add = "添加",
            edit = "編輯",
            settingsMenu = "選單",
            goals = "目標",
            newGoal = "新建目標",
            editGoal = "編輯目標",
            goalName = "名稱",
            goalNameHint = "輸入目標名稱",
            color = "顏色",
            icon = "圖示",
            startDate = "開始日期",
            endDate = "截止日期",
            progressMode = "進度統計",
            reasonDeleteGoal = "刪除該目標將同時刪除其下全部任務，確定刪除？",
            hanDoneCount = "已完成 {0} / {1}",
            countdown = "倒數計時",
            totalProgress = "總進度",
            noGoal = "暫無目標",
            noGoalHint = "點擊右下角按鈕新建一個目標吧",
            newTask = "新任務",
            addTask = "新增任務",
            addSubtask = "新增子任務",
            taskName = "任務名稱",
            taskNameHint = "輸入任務名稱",
            taskType = "類型",
            typeSingle = "單項",
            typeProgress = "進度",
            status = "狀態",
            total = "總量",
            current = "目前",
            reminderTime = "提醒時間",
            repeat = "重複",
            reasonDeleteTask = "確定刪除該任務？",
            reasonDeleteTaskCascade = "該任務包含子任務，刪除將一併刪除全部子任務，確定刪除？",
            reasonEdit = "編輯任務",
            statusNotDone = "未完成",
            statusHalfDone = "半完成",
            statusDone = "完成",
            statusDeleted = "刪除",
            settings = "設定",
            themeMode = "配色",
            colorScheme = "配色方案",
            language = "語言",
            skin = "皮膚",
            aiConfig = "AI 模型",
            aiBaseUrl = "Base URL",
            aiModelName = "模型名",
            apiKey = "API Key",
            apiKeyHint = "填寫你的 API Key",
            dataBackup = "資料備份",
            exportData = "匯出資料",
            importData = "匯入資料",
            aiCopilotNote = "Android 各廠商助手（小愛/Bixby/YOYO 等）無公開 API，故不內嵌。請設定 OpenAI 相容 API（預設 DeepSeek）即可在 AI 聊天中使用任務生成與對話能力。",
            aiChat = "AI 助手",
            aiChatHint = "描述你想規劃的事項，或上傳附件讓我生成任務清單",
            send = "傳送",
            attach = "附件",
            attaching = "正在解析附件…",
            generating = "AI 思考中…",
            aiError = "請求失敗，請檢查「AI 模型」設定中的組態與網路",
            themeSystem = "跟隨系統",
            themeLight = "亮色",
            themeDark = "暗色",
            langSystem = "跟隨系統",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val ja = Strings(
            appName = "Tick",
            save = "保存",
            cancel = "キャンセル",
            delete = "削除",
            confirm = "OK",
            back = "戻る",
            done = "完了",
            add = "追加",
            edit = "編集",
            settingsMenu = "メニュー",
            goals = "目標",
            newGoal = "新規目標",
            editGoal = "目標を編集",
            goalName = "名前",
            goalNameHint = "目標名を入力",
            color = "カラー",
            icon = "アイコン",
            startDate = "開始日",
            endDate = "期限日",
            progressMode = "進度の集計",
            reasonDeleteGoal = "この目標を削除すると配下のすべてのタスクも削除されます。削除しますか？",
            hanDoneCount = "{0} / {1} 件完了",
            countdown = "カウントダウン",
            totalProgress = "全体の進捗",
            noGoal = "目標がありません",
            noGoalHint = "右下のボタンをタップして目標を作成しましょう",
            newTask = "新規タスク",
            addTask = "タスクを追加",
            addSubtask = "サブタスクを追加",
            taskName = "タスク名",
            taskNameHint = "タスク名を入力",
            taskType = "種類",
            typeSingle = "単項目",
            typeProgress = "進捗",
            status = "ステータス",
            total = "合計量",
            current = "現在",
            reminderTime = "リマインダー時刻",
            repeat = "繰り返し",
            reasonDeleteTask = "このタスクを削除しますか？",
            reasonDeleteTaskCascade = "このタスクにはサブタスクが含まれています。削除するとすべてのサブタスクも削除されます。削除しますか？",
            reasonEdit = "タスクを編集",
            statusNotDone = "未完了",
            statusHalfDone = "半完了",
            statusDone = "完了",
            statusDeleted = "削除",
            settings = "設定",
            themeMode = "テーマ",
            colorScheme = "カラーテーマ",
            language = "言語",
            skin = "スキン",
            aiConfig = "AI モデル",
            aiBaseUrl = "Base URL",
            aiModelName = "モデル名",
            apiKey = "API Key",
            apiKeyHint = "API Key を入力してください",
            dataBackup = "データバックアップ",
            exportData = "データを書き出す",
            importData = "データを読み込む",
            aiCopilotNote = "Android 各メーカーのアシスタント（小愛/Bixby/YOYO など）は公開 API がないため、組み込んでいません。OpenAI 互換 API（デフォルトは DeepSeek）を設定すれば、AI チャットでタスク生成と会話機能を利用できます。",
            aiChat = "AI アシスタント",
            aiChatHint = "計画したい内容を説明するか、添付ファイルをアップロードしてタスクリストを生成させてください",
            send = "送信",
            attach = "添付",
            attaching = "添付ファイルを解析中…",
            generating = "AI 思考中…",
            aiError = "リクエストに失敗しました。「AI モデル」設定の構成とネットワークを確認してください",
            themeSystem = "システムに従う",
            themeLight = "ライト",
            themeDark = "ダーク",
            langSystem = "システムに従う",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val ko = Strings(
            appName = "Tick",
            save = "저장",
            cancel = "취소",
            delete = "삭제",
            confirm = "확인",
            back = "뒤로",
            done = "완료",
            add = "추가",
            edit = "편집",
            settingsMenu = "메뉴",
            goals = "목표",
            newGoal = "새 목표",
            editGoal = "목표 편집",
            goalName = "이름",
            goalNameHint = "목표 이름 입력",
            color = "색상",
            icon = "아이콘",
            startDate = "시작일",
            endDate = "마감일",
            progressMode = "진도 통계",
            reasonDeleteGoal = "이 목표를 삭제하면 하위 모든 작업도 함께 삭제됩니다. 삭제하시겠습니까?",
            hanDoneCount = "{0} / {1}개 완료",
            countdown = "카운트다운",
            totalProgress = "전체 진행률",
            noGoal = "목표 없음",
            noGoalHint = "오른쪽 아래 버튼을 눌러 목표를 만들어 보세요",
            newTask = "새 작업",
            addTask = "작업 추가",
            addSubtask = "하위 작업 추가",
            taskName = "작업 이름",
            taskNameHint = "작업 이름 입력",
            taskType = "유형",
            typeSingle = "단일 항목",
            typeProgress = "진행률",
            status = "상태",
            total = "총량",
            current = "현재",
            reminderTime = "알림 시간",
            repeat = "반복",
            reasonDeleteTask = "이 작업을 삭제하시겠습니까?",
            reasonDeleteTaskCascade = "이 작업에는 하위 작업이 포함되어 있습니다. 삭제하면 모든 하위 작업도 함께 삭제됩니다. 삭제하시겠습니까?",
            reasonEdit = "작업 편집",
            statusNotDone = "미완료",
            statusHalfDone = "반 완료",
            statusDone = "완료",
            statusDeleted = "삭제",
            settings = "설정",
            themeMode = "테마",
            colorScheme = "색상 테마",
            language = "언어",
            skin = "스킨",
            aiConfig = "AI 모델",
            aiBaseUrl = "Base URL",
            aiModelName = "모델명",
            apiKey = "API Key",
            apiKeyHint = "API Key를 입력하세요",
            dataBackup = "데이터 백업",
            exportData = "데이터 내보내기",
            importData = "데이터 가져오기",
            aiCopilotNote = "Android 각 제조사 어시스턴트(小愛/Bixby/YOYO 등)에는 공개 API가 없어 내장되어 있지 않습니다. OpenAI 호환 API(기본 DeepSeek)를 설정하면 AI 채팅에서 작업 생성과 대화 기능을 사용할 수 있습니다.",
            aiChat = "AI 어시스턴트",
            aiChatHint = "계획할 내용을 설명하거나 첨부 파일을 업로드하여 작업 목록을 생성하세요",
            send = "보내기",
            attach = "첨부",
            attaching = "첨부 파일을 분석 중…",
            generating = "AI가 생각하는 중…",
            aiError = "요청에 실패했습니다. 'AI 모델' 설정의 구성과 네트워크를 확인하세요",
            themeSystem = "시스템 따르기",
            themeLight = "라이트",
            themeDark = "다크",
            langSystem = "시스템 따르기",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val fr = Strings(
            appName = "Tick",
            save = "Enregistrer",
            cancel = "Annuler",
            delete = "Supprimer",
            confirm = "OK",
            back = "Retour",
            done = "Terminé",
            add = "Ajouter",
            edit = "Modifier",
            settingsMenu = "Menu",
            goals = "Objectifs",
            newGoal = "Nouvel objectif",
            editGoal = "Modifier l'objectif",
            goalName = "Nom",
            goalNameHint = "Saisissez le nom de l'objectif",
            color = "Couleur",
            icon = "Icône",
            startDate = "Date de début",
            endDate = "Date d'échéance",
            progressMode = "Suivi de la progression",
            reasonDeleteGoal = "Supprimer cet objectif supprime également toutes ses tâches. Supprimer ?",
            hanDoneCount = "{0} / {1} terminé(s)",
            countdown = "Compte à rebours",
            totalProgress = "Progression globale",
            noGoal = "Aucun objectif",
            noGoalHint = "Appuyez sur le bouton pour créer un objectif",
            newTask = "Nouvelle tâche",
            addTask = "Ajouter une tâche",
            addSubtask = "Ajouter une sous-tâche",
            taskName = "Nom de la tâche",
            taskNameHint = "Saisissez le nom de la tâche",
            taskType = "Type",
            typeSingle = "Ponctuel",
            typeProgress = "Progression",
            status = "Statut",
            total = "Quantité totale",
            current = "Actuel",
            reminderTime = "Heure de rappel",
            repeat = "Répétition",
            reasonDeleteTask = "Supprimer cette tâche ?",
            reasonDeleteTaskCascade = "Cette tâche contient des sous-tâches. Les supprimer les supprimera toutes. Supprimer ?",
            reasonEdit = "Modifier la tâche",
            statusNotDone = "Non terminé",
            statusHalfDone = "Partiellement terminé",
            statusDone = "Terminé",
            statusDeleted = "Supprimé",
            settings = "Réglages",
            themeMode = "Thème",
            colorScheme = "Nuancier",
            language = "Langue",
            skin = "Skin",
            aiConfig = "Modèle IA",
            aiBaseUrl = "Base URL",
            aiModelName = "Nom du modèle",
            apiKey = "API Key",
            apiKeyHint = "Saisissez votre API Key",
            dataBackup = "Sauvegarde des données",
            exportData = "Exporter les données",
            importData = "Importer des données",
            aiCopilotNote = "Les assistants des fabricants Android (Xiao Ai/Bixby/YOYO, etc.) n'exposent aucune API publique, aucun n'est donc intégré. Configurez une API compatible OpenAI (DeepSeek par défaut) pour utiliser la génération de tâches et la conversation dans l'assistant IA.",
            aiChat = "Assistant IA",
            aiChatHint = "Décrivez ce que vous voulez planifier, ou joignez un fichier pour générer une liste de tâches",
            send = "Envoyer",
            attach = "Pièce jointe",
            attaching = "Analyse de la pièce jointe…",
            generating = "L'IA réfléchit…",
            aiError = "Échec de la requête. Vérifiez la configuration des réglages « Modèle IA » et le réseau.",
            themeSystem = "Suivre le système",
            themeLight = "Clair",
            themeDark = "Sombre",
            langSystem = "Suivre le système",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val de = Strings(
            appName = "Tick",
            save = "Speichern",
            cancel = "Abbrechen",
            delete = "Löschen",
            confirm = "OK",
            back = "Zurück",
            done = "Erledigt",
            add = "Hinzufügen",
            edit = "Bearbeiten",
            settingsMenu = "Menü",
            goals = "Ziele",
            newGoal = "Neues Ziel",
            editGoal = "Ziel bearbeiten",
            goalName = "Name",
            goalNameHint = "Zielnamen eingeben",
            color = "Farbe",
            icon = "Symbol",
            startDate = "Startdatum",
            endDate = "Fälligkeitsdatum",
            progressMode = "Fortschrittsverfolgung",
            reasonDeleteGoal = "Das Löschen dieses Ziels löscht auch alle zugehörigen Aufgaben. Löschen?",
            hanDoneCount = "{0} / {1} erledigt",
            countdown = "Countdown",
            totalProgress = "Gesamtfortschritt",
            noGoal = "Keine Ziele",
            noGoalHint = "Tippen Sie auf die Schaltfläche, um ein Ziel zu erstellen",
            newTask = "Neue Aufgabe",
            addTask = "Aufgabe hinzufügen",
            addSubtask = "Unteraufgabe hinzufügen",
            taskName = "Aufgabenname",
            taskNameHint = "Aufgabennamen eingeben",
            taskType = "Typ",
            typeSingle = "Einmalig",
            typeProgress = "Fortschritt",
            status = "Status",
            total = "Gesamtmenge",
            current = "Aktuell",
            reminderTime = "Erinnerungszeit",
            repeat = "Wiederholung",
            reasonDeleteTask = "Diese Aufgabe löschen?",
            reasonDeleteTaskCascade = "Diese Aufgabe enthält Unteraufgaben. Beim Löschen werden alle mitgelöscht. Löschen?",
            reasonEdit = "Aufgabe bearbeiten",
            statusNotDone = "Nicht erledigt",
            statusHalfDone = "Teilweise erledigt",
            statusDone = "Erledigt",
            statusDeleted = "Gelöscht",
            settings = "Einstellungen",
            themeMode = "Design",
            colorScheme = "Farbschema",
            language = "Sprache",
            skin = "Skin",
            aiConfig = "KI-Modell",
            aiBaseUrl = "Base URL",
            aiModelName = "Modellname",
            apiKey = "API-Key",
            apiKeyHint = "Geben Sie Ihren API-Key ein",
            dataBackup = "Datensicherung",
            exportData = "Daten exportieren",
            importData = "Daten importieren",
            aiCopilotNote = "Die Assistenten der Android-Hersteller (Xiao Ai/Bixby/YOYO usw.) bieten keine öffentliche API, daher ist keiner integriert. Konfigurieren Sie eine OpenAI-kompatible API (standardmäßig DeepSeek), um die Aufgaben-Erstellung und den Chat im KI-Assistenten zu nutzen.",
            aiChat = "KI-Assistent",
            aiChatHint = "Beschreiben Sie, was Sie planen möchten, oder hängen Sie eine Datei an, um eine Aufgabenliste zu erstellen",
            send = "Senden",
            attach = "Anhang",
            attaching = "Anhang wird analysiert…",
            generating = "KI denkt nach…",
            aiError = "Anfrage fehlgeschlagen. Prüfen Sie die Konfiguration in den Einstellungen „KI-Modell“ und das Netzwerk.",
            themeSystem = "System folgen",
            themeLight = "Hell",
            themeDark = "Dunkel",
            langSystem = "System folgen",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        val es = Strings(
            appName = "Tick",
            save = "Guardar",
            cancel = "Cancelar",
            delete = "Eliminar",
            confirm = "Aceptar",
            back = "Atrás",
            done = "Hecho",
            add = "Añadir",
            edit = "Editar",
            settingsMenu = "Menú",
            goals = "Objetivos",
            newGoal = "Nuevo objetivo",
            editGoal = "Editar objetivo",
            goalName = "Nombre",
            goalNameHint = "Introduzca el nombre del objetivo",
            color = "Color",
            icon = "Icono",
            startDate = "Fecha de inicio",
            endDate = "Fecha límite",
            progressMode = "Seguimiento del progreso",
            reasonDeleteGoal = "Eliminar este objetivo también elimina todas sus tareas. ¿Eliminar?",
            hanDoneCount = "{0} / {1} completadas",
            countdown = "Cuenta atrás",
            totalProgress = "Progreso general",
            noGoal = "Sin objetivos",
            noGoalHint = "Toque el botón para crear un objetivo",
            newTask = "Nueva tarea",
            addTask = "Añadir tarea",
            addSubtask = "Añadir subtarea",
            taskName = "Nombre de la tarea",
            taskNameHint = "Introduzca el nombre de la tarea",
            taskType = "Tipo",
            typeSingle = "Único",
            typeProgress = "Progreso",
            status = "Estado",
            total = "Cantidad total",
            current = "Actual",
            reminderTime = "Hora del recordatorio",
            repeat = "Repetición",
            reasonDeleteTask = "¿Eliminar esta tarea?",
            reasonDeleteTaskCascade = "Esta tarea contiene subtareas. Eliminarla eliminará todas. ¿Eliminar?",
            reasonEdit = "Editar tarea",
            statusNotDone = "Sin hacer",
            statusHalfDone = "A medias",
            statusDone = "Hecho",
            statusDeleted = "Eliminado",
            settings = "Ajustes",
            themeMode = "Tema",
            colorScheme = "Esquema de color",
            language = "Idioma",
            skin = "Skin",
            aiConfig = "Modelo de IA",
            aiBaseUrl = "Base URL",
            aiModelName = "Nombre del modelo",
            apiKey = "API Key",
            apiKeyHint = "Introduzca su API Key",
            dataBackup = "Copia de seguridad de datos",
            exportData = "Exportar datos",
            importData = "Importar datos",
            aiCopilotNote = "Los asistentes de los fabricantes de Android (Xiao Ai/Bixby/YOYO, etc.) no exponen una API pública, por lo que no se incluye ninguno. Configure una API compatible con OpenAI (DeepSeek por defecto) para usar la generación de tareas y el chat en el asistente de IA.",
            aiChat = "Asistente de IA",
            aiChatHint = "Describa lo que desea planificar o adjunte un archivo para generar una lista de tareas",
            send = "Enviar",
            attach = "Adjunto",
            attaching = "Analizando el archivo adjunto…",
            generating = "La IA está pensando…",
            aiError = "Error en la solicitud. Compruebe la configuración de «Modelo de IA» y la red.",
            themeSystem = "Seguir el sistema",
            themeLight = "Claro",
            themeDark = "Oscuro",
            langSystem = "Seguir el sistema",
            langZh = "简体中文",
            langZhHant = "繁體中文",
            langJa = "日本語",
            langKo = "한국어",
            langEn = "English",
            langFr = "Français",
            langDe = "Deutsch",
            langEs = "Español"
        )

        fun of(language: AppLanguage): Strings = when (language) {
            AppLanguage.ZH_HANS -> zh
            AppLanguage.ZH_HANT -> zhHant
            AppLanguage.JA -> ja
            AppLanguage.KO -> ko
            AppLanguage.EN -> en
            AppLanguage.FR -> fr
            AppLanguage.DE -> de
            AppLanguage.ES -> es
            AppLanguage.SYSTEM -> zh
        }
    }
}

/** 提供当前语言的最合适 TextView 统一文本；供全局访问 */
val LocalStrings = staticCompositionLocalOf { Strings.zh }