package com.tick.app.android.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.tick.app.android.model.AppLanguage

/** 应用的轻量本地化字符串（简体中文 / English）。 */
data class Strings(
    // 通用
    val appName: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val confirm: String,
    val back: String,
    val done: String,
    val add: String,
    val edit: String,
    val settingsMenu: String,
    // 侧边栏 / 目标
    val goals: String,
    val newGoal: String,
    val editGoal: String,
    val goalName: String,
    val goalNameHint: String,
    val color: String,
    val icon: String,
    val startDate: String,
    val endDate: String,
    val progressMode: String,
    val reasonDeleteGoal: String,
    val hanDoneCount: String,
    val countdown: String,
    val totalProgress: String,
    val noGoal: String,
    val noGoalHint: String,
    // 任务
    val newTask: String,
    val addTask: String,
    val addSubtask: String,
    val taskName: String,
    val taskNameHint: String,
    val taskType: String,
    val typeSingle: String,
    val typeProgress: String,
    val status: String,
    val total: String,
    val current: String,
    val reminderTime: String,
    val repeat: String,
    val reasonDeleteTask: String,
    val reasonDeleteTaskCascade: String,
    val reasonEdit: String,
    val statusNotDone: String,
    val statusHalfDone: String,
    val statusDone: String,
    val statusDeleted: String,
    // 设置
    val settings: String,
    val themeMode: String,
    val colorScheme: String,
    val language: String,
    val skin: String,
    val aiConfig: String,
    val aiBaseUrl: String,
    val aiModelName: String,
    val apiKey: String,
    val apiKeyHint: String,
    val dataBackup: String,
    val exportData: String,
    val importData: String,
    val hyperosGlassNote: String,
    val aiCopilotNote: String,
    // AI 聊天
    val aiChat: String,
    val aiChatHint: String,
    val send: String,
    val attach: String,
    val attaching: String,
    val generating: String,
    val aiError: String,
    // 语言/配色选项
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val langSystem: String,
    val langZh: String,
    val langEn: String
) {
    companion object {
        val zh = Strings(
            appName = "Tick",
            save = "保存",
            cancel = "取消",
            delete = "删除",
            confirm = "确定",
            back = "返回",
            done = "完成",
            add = "添加",
            edit = "编辑",
            settingsMenu = "菜单",
            goals = "目标",
            newGoal = "新建目标",
            editGoal = "编辑目标",
            goalName = "名称",
            goalNameHint = "输入目标名称",
            color = "颜色",
            icon = "图标",
            startDate = "开始日期",
            endDate = "截止日期",
            progressMode = "进度统计",
            reasonDeleteGoal = "删除该目标将同时删除其下全部任务，确定删除？",
            hanDoneCount = "已完成 {0} / {1}",
            countdown = "倒计时",
            totalProgress = "总进度",
            noGoal = "暂无目标",
            noGoalHint = "点击右下角按钮新建一个目标吧",
            newTask = "新建任务",
            addTask = "添加任务",
            addSubtask = "添加子任务",
            taskName = "任务名称",
            taskNameHint = "输入任务名称",
            taskType = "类型",
            typeSingle = "单项",
            typeProgress = "进度",
            status = "状态",
            total = "总量",
            current = "当前",
            reminderTime = "提醒时间",
            repeat = "重复",
            reasonDeleteTask = "确定删除该任务？",
            reasonDeleteTaskCascade = "该任务包含子任务，删除将一并删除全部子任务，确定删除？",
            reasonEdit = "编辑任务",
            statusNotDone = "未完成",
            statusHalfDone = "半完成",
            statusDone = "完成",
            statusDeleted = "删除",
            settings = "设置",
            themeMode = "配色",
            colorScheme = "配色方案",
            language = "语言",
            skin = "皮肤",
            aiConfig = "AI 模型",
            aiBaseUrl = "Base URL",
            aiModelName = "模型名",
            apiKey = "API Key",
            apiKeyHint = "填写你的 API Key",
            dataBackup = "数据备份",
            exportData = "导出数据",
            importData = "导入数据",
            hyperosGlassNote = "玻璃橙皮肤采用橙色半透明玻璃质感",
            aiCopilotNote = "Android 各厂商助手（小爱/Bixby/YOYO 等）无公开 API，故不内嵌。请配置 OpenAI 兼容 API（默认 DeepSeek）即可在 AI 聊天中使用任务生成与对话能力。",
            aiChat = "AI 助手",
            aiChatHint = "描述你想规划的事项，或上传附件让我生成任务清单",
            send = "发送",
            attach = "附件",
            attaching = "正在解析附件…",
            generating = "AI 思考中…",
            aiError = "请求失败，请检查设置在“AI 模型”中的配置与网络",
            themeSystem = "跟随系统",
            themeLight = "亮色",
            themeDark = "暗色",
            langSystem = "跟随系统",
            langZh = "简体中文",
            langEn = "English"
        )

        val en = Strings(
            appName = "Tick",
            save = "Save",
            cancel = "Cancel",
            delete = "Delete",
            confirm = "OK",
            back = "Back",
            done = "Done",
            add = "Add",
            edit = "Edit",
            settingsMenu = "Menu",
            goals = "Goals",
            newGoal = "New Goal",
            editGoal = "Edit Goal",
            goalName = "Name",
            goalNameHint = "Enter goal name",
            color = "Color",
            icon = "Icon",
            startDate = "Start date",
            endDate = "Due date",
            progressMode = "Progress mode",
            reasonDeleteGoal = "Deleting this goal also deletes all its tasks. Delete?",
            hanDoneCount = "{0} / {1} done",
            countdown = "Countdown",
            totalProgress = "Progress",
            noGoal = "No Goals",
            noGoalHint = "Tap the button to create a goal",
            newTask = "New Task",
            addTask = "Add Task",
            addSubtask = "Add Subtask",
            taskName = "Task name",
            taskNameHint = "Enter task name",
            taskType = "Type",
            typeSingle = "Single",
            typeProgress = "Progress",
            status = "Status",
            total = "Total",
            current = "Current",
            reminderTime = "Reminder time",
            repeat = "Repeat",
            reasonDeleteTask = "Delete this task?",
            reasonDeleteTaskCascade = "This task has subtasks. Deleting removes them too. Delete?",
            reasonEdit = "Edit Task",
            statusNotDone = "Not done",
            statusHalfDone = "Half done",
            statusDone = "Done",
            statusDeleted = "Deleted",
            settings = "Settings",
            themeMode = "Theme",
            colorScheme = "Color scheme",
            language = "Language",
            skin = "Skin",
            aiConfig = "AI Model",
            aiBaseUrl = "Base URL",
            aiModelName = "Model",
            apiKey = "API Key",
            apiKeyHint = "Enter your API Key",
            dataBackup = "Data Backup",
            exportData = "Export data",
            importData = "Import data",
            hyperosGlassNote = "Glass Orange skin uses an orange translucent glass look",
            aiCopilotNote = "Android assistants (Xiao Ai/Bixby/YOYO, etc.) expose no public API, so none is bundled. Configure an OpenAI-compatible API (DeepSeek by default) to use task generation and chat in the AI assistant.",
            aiChat = "AI Assistant",
            aiChatHint = "Describe what to plan, or attach a file to generate a task list",
            send = "Send",
            attach = "Attach",
            attaching = "Parsing attachment…",
            generating = "AI is thinking…",
            aiError = "Request failed. Check the AI Model settings and your network.",
            themeSystem = "System",
            themeLight = "Light",
            themeDark = "Dark",
            langSystem = "System",
            langZh = "简体中文",
            langEn = "English"
        )

        fun of(language: AppLanguage): Strings = when (language) {
            AppLanguage.EN -> en
            else -> zh
        }
    }
}

/** 提供当前语言的最合适 TextView 统一文本；供全局访问 */
val LocalStrings = staticCompositionLocalOf { Strings.zh }